In [445]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.patches as mpatches
%matplotlib inline
plt.style.use('ggplot')

# Pre-Processing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler, OneHotEncoder, PolynomialFeatures

# Metrics
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_validate, ShuffleSplit
import statsmodels.api as sm
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error


pd.set_option('display.max_columns', None)


## Documentation

For a comprehensive list describing all the features/statistics in this notebook; refer to this documentation link from <a href = 'https://library.fangraphs.com/offense/offensive-statistics-list/'> FanGraphs </a> for basic and advanced statistics descriptions. 

## Batting Data

The `batting_stats` function returns basic and advanced season-level batting data from FanGraphs. 

While this query should work for any historical season, some of the more modern stats (contact %, zone %, and many others) will not be available before certain dates. 

*A note about the statistics being queried: most of the advanced level statistics will not be available before 2014 because <a href = 'https://www.mlb.com/glossary/statcast'> StatCast </a> was not introduced yet.*

In [446]:
from pybaseball import batting_stats

In [447]:
# retrieve data on only players who have 50+ plate appearances between 1990 and 2021
# batting_2021 = batting_stats(2000, 2021, qual=50)

In [448]:
# load in csv
batting_2021 = pd.read_csv('Data/batting_2021', index_col = 0)

In [449]:
batting_2021.head()

IDfg  Season          Name Team  Age    G   AB   PA    H  1B  2B  3B  HR  \
0    1109    2002   Barry Bonds  SFG   37  143  403  612  149  70  31   2  46   
2    1109    2001   Barry Bonds  SFG   36  153  476  664  156  49  32   2  73   
1    1109    2004   Barry Bonds  SFG   39  147  373  617  135  60  27   3  45   
38  13611    2018  Mookie Betts  BOS   25  136  520  614  180  96  47   5  32   
3    1109    2003   Barry Bonds  SFG   38  130  390  550  133  65  22   1  45   

      R  RBI   BB  IBB  SO  HBP  SF  SH  GDP  SB  CS    AVG     GB     FB  \
0   117  110  198   68  47    9   2   0    4   9   2  0.370  109.0  169.0   
2   129  137  177   35  93    9   2   0    5  13   3  0.328    NaN    NaN   
1   129  101  232  120  41    9   3   0    5   6   1  0.362  117.0  156.0   
38  129   80   81    8  91    8   5   0    5  30   6  0.346  147.0  195.0   
3   111   90  148   61  58   10   2   0    7   7   0  0.341  101.0  152.0   

      LD  IFFB  Pitches   Balls  Strikes   IFH   BU  BUH    BB%     K%  BB/K  \
0   80.0  16.0   2398.0  1336.0   1062.0   5.0  0.0  0.0  0.324  0.077  4.21   
2    NaN   NaN      NaN     NaN      NaN   NaN  NaN  NaN  0.267  0.140  1.90   
1   62.0  22.0   2425.0  1444.0    981.0   8.0  0.0  0.0  0.376  0.066  5.66   
38  92.0  18.0   2582.0  1095.0   1487.0  14.0  0.0  0.0  0.132  0.148  0.89   
3   81.0  21.0   2175.0  1141.0   1034.0   7.0  0.0  0.0  0.269  0.105  2.55   

      OBP    SLG    OPS    ISO  BABIP   GB/FB    LD%    GB%    FB%  IFFB%  \
0   0.582  0.799  1.381  0.429  0.330  0.0064  0.223  0.304  0.472  0.095   
2   0.515  0.863  1.379  0.536  0.266     NaN    NaN    NaN    NaN    NaN   
1   0.609  0.812  1.422  0.450  0.310  0.0075  0.185  0.349  0.466  0.141   
38  0.438  0.640  1.078  0.294  0.368  0.0075  0.212  0.339  0.449  0.092   
3   0.529  0.749  1.278  0.408  0.304  0.0066  0.243  0.302  0.455  0.138   

    HR/FB   IFH%  BUH%   wOBA   wRAA  wRC    Bat   Fld   Rep  Pos    RAR  \
0   0.272  0.046   0.0  0.544  110.0  183  110.1   4.3  18.6 -6.3  126.8   
2     NaN    NaN   NaN  0.537  117.7  200  116.8  -5.0  20.7 -7.0  127.8   
1   0.288  0.068   0.0  0.537  108.0  185  106.0   2.2  19.1 -6.6  122.1   
38  0.164  0.095   0.0  0.449   67.2  139   62.4  18.5  18.4 -5.3  103.3   
3   0.296  0.069   0.0  0.503   80.5  148   79.3  11.6  17.0 -6.0  103.6   

     WAR    Dol  Spd  wRC+    WPA  -WPA   +WPA    RE24    REW   pLI  phLI  PH  \
0   12.7  $49.5  3.9   244  10.51 -5.90  16.40  118.51  12.63  0.98  3.23   4   
2   12.5    NaN  4.1   235  11.63 -7.46  19.10  118.93  12.11  0.97  1.34   5   
1   11.9  $49.9  4.0   233  13.06 -5.23  18.29  128.94  12.86  1.04  2.18   8   
38  10.6  $85.1  7.0   185   5.77 -8.16  13.93   62.93   6.11  0.92  3.62   4   
3   10.2  $43.9  3.9   212   7.99 -5.94  13.93   84.65   8.61  0.99  2.36   2   

    WPA/LI  Clutch  FB% (Pitch)   FBv    SL%   SLv    CT%   CTv    CB%   CBv  \
0    11.82   -1.11        0.678  89.0  0.108  79.9    NaN   NaN  0.081  74.2   
2    13.04   -1.04          NaN   NaN    NaN   NaN    NaN   NaN    NaN   NaN   
1    11.35    1.15        0.607  90.1  0.136  82.7  0.005  88.3  0.094  75.2   
38    6.44   -0.15        0.547  93.2  0.199  84.5  0.050  88.7  0.073  79.1   
3     8.38   -0.34        0.629  89.5  0.128  80.3    NaN   NaN  0.088  74.9   

      CH%   CHv    SF%   SFv    KN%   KNv    XX%    PO%   wFB   wSL  wCT  \
0   0.107  76.5  0.026  80.5    NaN   NaN  0.081    NaN  67.8  12.5  NaN   
2     NaN   NaN    NaN   NaN    NaN   NaN    NaN    NaN   NaN   NaN  NaN   
1   0.129  81.9  0.022  80.6  0.008  74.2  0.184  0.059  52.6   8.3  1.7   
38  0.114  84.4  0.017  85.4    NaN   NaN  0.009    NaN  40.1  11.2  4.2   
3   0.135  80.5  0.019  82.6  0.001   NaN  0.109    NaN  52.6   3.5  NaN   

     wCB   wCH  wSF  wKN  wFB/C  wSL/C  wCT/C  wCB/C  wCH/C  wSF/C  wKN/C  \
0    5.1  19.2  0.8  NaN   4.54   5.27    NaN   2.84   8.13   1.37    NaN   
2    NaN   NaN  NaN  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  

In [450]:
batting_2021.describe()

IDfg        Season           Age             G            AB  \
count  1.200600e+04  12006.000000  12006.000000  12006.000000  12006.000000   
mean   1.968213e+04   2010.426287     28.612360     89.841163    287.096535   
std    1.194781e+05      6.292497      4.150018     45.450986    186.734319   
min    1.000000e+00   2000.000000     19.000000     12.000000     36.000000   
25%    1.036250e+03   2005.000000     25.000000     45.000000    112.000000   
50%    3.311000e+03   2010.000000     28.000000     90.000000    252.000000   
75%    9.063000e+03   2016.000000     31.000000    133.000000    456.000000   
max    1.014462e+06   2021.000000     48.000000    163.000000    716.000000   

                 PA             H            1B            2B            3B  \
count  12006.000000  12006.000000  12006.000000  12006.000000  12006.000000   
mean     321.890222     75.034566     49.217475     15.011827      1.537731   
std      209.826797     54.883957     36.203340     11.825252      2.104999   
min       50.000000      0.000000      0.000000      0.000000      0.000000   
25%      124.250000     26.000000     17.000000      5.000000      0.000000   
50%      281.500000     63.000000     41.000000     12.000000      1.000000   
75%      510.000000    120.000000     77.000000     24.000000      2.000000   
max      778.000000    262.000000    225.000000     59.000000     23.000000   

                 HR             R           RBI            BB           IBB  \
count  12006.000000  12006.000000  12006.000000  12006.000000  12006.000000   
mean       9.267533     38.859487     37.125354     27.449858      1.996335   
std        9.829529     30.438054     30.640863     23.689191      3.634348   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        2.000000     13.000000     11.000000      9.000000      0.000000   
50%        6.000000     31.000000     29.000000     21.000000      1.000000   
75%       14.000000     61.000000     57.000000     40.000000      3.000000   
max       73.000000    152.000000    160.000000    232.000000    120.000000   

                 SO           HBP            SF            SH           GDP  \
count  12006.000000  12006.000000  12006.000000  12006.000000  12006.000000   
mean      60.077794      3.039064      2.275612      1.979927      6.479594   
std       39.375700      3.574619      2.344524      2.946817      5.564244   
min        2.000000      0.000000      0.000000      0.000000      0.000000   
25%       27.000000      0.000000      0.000000      0.000000      2.000000   
50%       52.000000      2.000000      2.000000      1.000000      5.000000   
75%       85.000000      4.000000      3.000000      3.000000     10.000000   
max      223.000000     31.000000     16.000000     24.000000     32.000000   

                 SB            CS           AVG            GB            FB  \
count  12006.000000  12006.000000  12006.000000  10901.000000  10901.000000   
mean       4.790105      1.881309      0.242474     98.832492     80.735162   
std        7.994766      2.619757      0.052402     69.581627     59.382214   
min        0.000000      0.000000      0.000000      2.000000      0.000000   
25%        0.000000      0.000000      0.218000     37.000000     28.000000   
50%        2.000000      1.000000      0.251000     84.000000     68.000000   
75%        6.000000      3.000000      0.277000    151.000000    126.000000   
max       78.000000     24.000000      0.397000    401.000000    285.000000   

                 LD          IFFB       Pitches         Balls       Strikes  \
count  10901.000000  10901.000000  10901.000000  10901.000000  10901.000000   
mean      46.287130      8.217503   1228.572791    454.508302    774.064489   
std       33.773407      7.468154    809.704250    316.561484    498.733437   
min        0.000000      0.000000    136.000000     22.000000     94.000000   
25%       16.000000      2.000000    476.000000    169.00000

## bWAR Batting

Get Baseball Reference's WAR stats from its war_daily_bat table, along with some other data that's not included in the batting_stats_bref function. 

For the purposes of this project, we will care about salary, WAR, and the above average columns. We can later merge this dataframe with the `batting_2022` dataframe.

In [451]:
from pybaseball import bwar_bat

# get war stats from baseball reference 
bwar_bat = bwar_bat()
bwar_bat.head()

name_common    mlb_ID  player_ID  year_ID team_ID  stint_ID lg_ID  \
0  David Aardsma  430911.0  aardsda01     2004     SFG         1    NL   
1  David Aardsma  430911.0  aardsda01     2006     CHC         1    NL   
2  David Aardsma  430911.0  aardsda01     2007     CHW         1    AL   
3  David Aardsma  430911.0  aardsda01     2008     BOS         1    AL   
4  David Aardsma  430911.0  aardsda01     2009     SEA         1    AL   

  pitcher   G   PA    salary  runs_above_avg  runs_above_avg_off  \
0       Y  11  0.0  300000.0             0.0                 0.0   
1       Y  43  3.0       NaN            -0.4                -0.4   
2       Y   2  0.0  387500.0             0.0                 0.0   
3       Y   5  1.0  403250.0            -0.2                -0.2   
4       Y   3  0.0  419000.0             0.0                 0.0   

   runs_above_avg_def  WAR_rep   WAA   WAR  
0                 0.0      0.0  0.00  0.00  
1                 0.0      0.0 -0.04 -0.04  
2                 0.0      0.0  0.00  0.00  
3                 0.0      0.0 -0.02 -0.02  
4                 0.0      0.0  0.00  0.00

In [452]:
# load in csv
bwar_bat = pd.read_csv('Data/bwar_bat', index_col = 0)

In [453]:
# filter bwar_bat to 2000 - 2021 and minimum 50 PA
bwar_bat_2021 = bwar_bat[(bwar_bat['year_ID'].between(2000,2021)) & (bwar_bat['PA'] >= 50)]
bwar_bat_2021.sort_values(by = 'year_ID')

name_common    mlb_ID  player_ID  year_ID team_ID  stint_ID  \
109          Jeff Abbott  110010.0  abbotje01     2000     CHW         1   
86775         Tom Prince  120771.0  princto01     2000     PHI         1   
33254        Robert Fick  137001.0   fickro01     2000     DET         1   
32714      Carlos Febles  136866.0  febleca01     2000     KCR         1   
32656         Sal Fasano  114031.0  fasansa01     2000     OAK         1   
...                  ...       ...        ...      ...     ...       ...   
96813     Kyle Schwarber  656941.0  schwaky01     2021     BOS         2   
96814     Kyle Schwarber  656941.0  schwaky01     2021     WSN         1   
96832    Frank Schwindel  643524.0  schwifr01     2021     CHC         2   
23298   Jake Cronenworth  630105.0  croneja01     2021     SDP         1   
119788       Mike Zunino  572287.0  zuninmi01     2021     TBR         1   

       lg_ID pitcher    G     PA     salary  runs_above_avg  \
109       AL       N   80  242.0   255000.0           -12.6   
86775     NL       N   46  140.0   300000.0            -4.2   
33254     AL       N   66  188.0   200000.0            -5.3   
32714     AL       N  100  399.0   250000.0             2.8   
32656     AL       N   52  144.0   240000.0             1.0   
...      ...     ...  ...    ...        ...             ...   
96813     AL       N   41  168.0        NaN             7.5   
96814     NL       N   72  303.0  7000000.0             8.8   
96832     NL       N   56  239.0        NaN            10.1   
23298     NL       N  152  643.0        NaN            27.7   
119788    AL       N  109  375.0  2000000.0            24.5   

        runs_above_avg_off  runs_above_avg_def  WAR_rep   WAA   WAR  
109                   -6.7                -7.3     0.84 -1.13 -0.29  
86775                 -4.2                 2.3     0.42 -0.44 -0.02  
33254                 -5.6                -1.8     0.65 -0.47  0.18  
32714                 -3.6                 8.9     1.39  0.31  1.70  
32656                  0.0                 3.5     0.50  0.11  0.61  
...                    ...                 ...      ...   ...   ...  
96813                 10.5                -5.4     0.56  0.77  1.33  
96814                 13.8                -7.5     1.02  0.81  1.83  
96832                 14.1                -7.1     0.80  0.95  1.75  
23298                 22.7                 8.5     2.16  2.64  4.80  
119788                25.5                 5.4     1.25  2.50  3.75  

[12616 rows x 17 columns]

In [454]:
bwar_bat_2021.describe()

mlb_ID       year_ID      stint_ID             G            PA  \
count   12616.000000  12616.000000  12616.000000  12616.000000  12616.000000   
mean   378575.647987   2010.391011      1.071100     84.781706    305.154011   
std    180548.349417      6.296166      0.269057     45.605022    206.944329   
min    110010.000000   2000.000000      1.000000     12.000000     50.000000   
25%    150148.000000   2005.000000      1.000000     41.000000    115.000000   
50%    430965.000000   2010.000000      1.000000     81.000000    253.000000   
75%    506942.250000   2016.000000      1.000000    128.000000    482.000000   
max    683734.000000   2021.000000      4.000000    163.000000    778.000000   

             salary  runs_above_avg  runs_above_avg_off  runs_above_avg_def  \
count  9.354000e+03    12616.000000        12616.000000        12616.000000   
mean   4.163878e+06        0.570799            0.563475            0.002949   
std    5.419254e+06       13.837667           12.055243            7.627333   
min    1.000000e+00      -50.400000          -42.400000          -50.700000   
25%    5.104250e+05       -7.300000           -6.300000           -3.700000   
50%    1.750000e+06       -1.600000           -1.600000            0.100000   
75%    5.900000e+06        5.100000            4.400000            3.300000   
max    3.833333e+07      106.300000          110.900000           49.300000   

            WAR_rep           WAA           WAR  
count  12616.000000  12616.000000  12616.000000  
mean       0.982166      0.044187      1.026352  
std        0.700321      1.399351      1.776108  
min        0.000000     -5.040000     -3.250000  
25%        0.380000     -0.750000     -0.140000  
50%        0.820000     -0.170000      0.460000  
75%        1.580000      0.520000      1.720000  
max        2.520000      9.880000     11.850000

In [455]:
# how many missing values in batting salary column?
print("Missing bWAR Batting Salary Data:")
bwar_bat_2021['salary'].isna().value_counts(normalize = True)

Missing bWAR Batting Salary Data:


False    0.741439
True     0.258561
Name: salary, dtype: float64

## Pitching Data

The `pitching_stats` function returns basic and advanced season-level pitching data from FanGraphs.

While this query should work for any historical season, some of the more modern stats (contact %, zone %, and many others) will not be available before certain dates.

In [456]:
from pybaseball import pitching_stats

In [457]:
# retrieve data on only players who have pitched 20+ innings since 2000
pitching_2021 = pitching_stats(2000, 2021, qual=20)

In [458]:
# load in csv
pitching_2021 = pd.read_csv('Data/pitching_2021', index_col = 0)

In [459]:
pitching_2021.head()

IDfg  Season            Name Team  Age   W   L   WAR   ERA   G  GS  CG  \
910     60    2001   Randy Johnson  ARI   37  21   6  10.4  2.49  35  34   3   
1152    60    2000   Randy Johnson  ARI   36  19   7   9.6  2.64  35  35   8   
1062    60    2004   Randy Johnson  ARI   40  16  14   9.6  2.60  35  35   4   
209    200    2000  Pedro Martinez  BOS   28  18   6   9.4  1.74  29  29   7   
2393    73    2002  Curt Schilling  ARI   35  23   7   9.3  3.23  36  35   5   

      ShO  SV   BS     IP   TBF    H   R  ER  HR  BB  IBB  HBP  WP  BK   SO  \
910     2   0  NaN  249.2   994  181  74  69  19  71    2   18   8   1  372   
1152    3   0  NaN  248.2  1001  202  89  73  23  76    1    6   5   2  347   
1062    2   0  0.0  245.2   964  177  88  71  18  44    1   10   3   1  290   
209     4   0  NaN  217.0   817  128  44  42  17  32    0   14   1   0  284   
2393    1   0  0.0  259.1  1017  218  95  93  29  33    1    3   6   0  316   

         GB     FB     LD  IFFB   Balls  Strikes  Pitches     RS   IFH    BU  \
910     NaN    NaN    NaN   NaN     NaN      NaN      NaN    NaN   NaN   NaN   
1152    NaN    NaN    NaN   NaN     NaN      NaN      NaN    NaN   NaN   NaN   
1062  261.0  224.0  120.0  24.0  1125.0   2508.0   3633.0  109.0  21.0  15.0   
209     NaN    NaN    NaN   NaN     NaN      NaN      NaN    NaN   NaN   NaN   
2393  272.0  235.0  143.0  26.0  1092.0   2630.0   3722.0  171.0  16.0  15.0   

      BUH    K/9  BB/9  K/BB   H/9  HR/9    AVG  WHIP  BABIP   LOB%   FIP  \
910   NaN  13.41  2.56  5.24  6.52  0.68  0.200  1.01  0.315  0.805  2.13   
1152  NaN  12.56  2.75  4.57  7.31  0.83  0.220  1.12  0.326  0.774  2.53   
1062  4.0  10.62  1.61  6.59  6.48  0.66  0.195  0.90  0.264  0.695  2.30   
209   NaN  11.78  1.33  8.88  5.31  0.71  0.166  0.74  0.236  0.866  2.17   
2393  3.0  10.97  1.15  9.58  7.57  1.01  0.222  0.97  0.297  0.745  2.40   

      GB/FB    LD%    GB%    FB%  IFFB%  HR/FB   IFH%   BUH%  Starting  \
910     NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN      86.4   
1152    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN      90.1   
1062   1.17  0.198  0.431  0.370  0.107  0.080  0.080  0.267      86.1   
209     NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN      87.1   
2393   1.16  0.220  0.418  0.362  0.111  0.123  0.059  0.200      81.9   

      Start-IP  Relieving  Relief-IP   RAR Dollars  tERA  xFIP   WPA   -WPA  \
910      242.2        4.5        7.0  90.9     NaN   NaN   NaN  6.23 -14.23   
1152     248.2        NaN        NaN  90.1     NaN   NaN   NaN  5.38 -15.87   
1062     245.2        NaN        NaN  86.1   $40.3  2.72  2.64  4.00 -14.28   
209      217.0        NaN        NaN  87.1     NaN   NaN   NaN  7.61  -9.24   
2393     258.1       -0.5        1.0  81.3   $36.3  3.10  2.20  4.63 -13.43   

       +WPA   RE24   REW   pLI  inLI  gmLI  exLI  Pulls  WPA/LI  Clutch  \
910   20.46  64.42  6.25  1.04  0.98  0.88  1.07     31    5.84    0.17   
1152  21.24  50.15  4.82  1.08  0.99  0.87  1.15     27    4.41    0.57   
1062  18.28  48.07  4.59  0.98  0.99  0.87  1.38     31    6.25   -2.16   
209   16.86  80.32  7.51  0.97  0.97  0.87  1.05     22    8.09   -0.25   
2393  18.06  43.62  4.27  0.90  0.93  0.84  1.23     31    6.01   -0.88   

      FB% 2   FBv    SL%   SLv  CT%  CTv    CB%   CBv    CH%   CHv    SF%  \
910     NaN   NaN    NaN   NaN  NaN  NaN    NaN   NaN    NaN   NaN    NaN   
1152    NaN   NaN    NaN   NaN  NaN  NaN    NaN   NaN    NaN   NaN    NaN   
1062  0.453  93.7  0.436  84.4  NaN  NaN    NaN   NaN  0.067  85.1  0.045   
209     NaN   NaN    NaN   NaN  NaN  NaN    NaN   NaN    NaN   NaN    NaN   
2393  0.552  92.7  0.126  85.6  NaN  NaN  0.055  75.5  0.042  83.4  0.224   

       SFv  KN%  KNv    XX%    PO%   wFB   wSL  wCT  wCB  wCH   wSF  wKN  \
910    NaN  NaN  NaN    NaN    NaN   NaN   NaN  NaN  NaN  NaN   NaN  NaN   
1152   NaN  NaN  NaN    NaN    NaN   NaN   NaN  NaN  NaN  NaN   NaN  NaN   
1062  85.7  NaN  NaN  0.098  0.001  11.0  33

In [460]:
pitching_2021.describe()

IDfg        Season           Age             W             L  \
count  1.051900e+04  10519.000000  10519.000000  10519.000000  10519.000000   
mean   1.975712e+04   2010.736287     28.348988      4.818994      4.739519   
std    1.173236e+05      6.307353      4.166458      4.397048      3.761656   
min    3.000000e+00   2000.000000     19.000000      0.000000      0.000000   
25%    1.138000e+03   2005.000000     25.000000      2.000000      2.000000   
50%    4.138000e+03   2011.000000     28.000000      3.000000      4.000000   
75%    9.810000e+03   2016.000000     31.000000      7.000000      7.000000   
max    1.014446e+06   2021.000000     49.000000     24.000000     21.000000   

                WAR           ERA             G            GS            CG  \
count  10519.000000  10519.000000  10519.000000  10519.000000  10519.000000   
mean       0.897604      4.325571     36.068257      9.703964      0.271604   
std        1.359167      1.492954     20.009926     12.012686      0.830297   
min       -1.600000      0.000000      4.000000      0.000000      0.000000   
25%        0.000000      3.320000     21.000000      0.000000      0.000000   
50%        0.500000      4.180000     32.000000      3.000000      0.000000   
75%        1.400000      5.155000     52.000000     19.000000      0.000000   
max       10.400000     13.140000     94.000000     36.000000     11.000000   

                ShO            SV           BS            IP           TBF  \
count  10519.000000  10519.000000  9638.000000  10519.000000  10519.000000   
mean       0.112558      2.438350     1.142457     84.111237    360.855405   
std        0.412157      7.643958     1.826539     58.102023    243.855154   
min        0.000000      0.000000     0.000000     20.000000     75.000000   
25%        0.000000      0.000000     0.000000     40.200000    179.000000   
50%        0.000000      0.000000     0.000000     64.000000    271.000000   
75%        0.000000      1.000000     2.000000    115.000000    499.000000   
max        6.000000     62.000000    12.000000    266.000000   1071.000000   

                  H             R            ER            HR            BB  \
count  10519.000000  10519.000000  10519.000000  10519.000000  10519.000000   
mean      82.872802     42.376652     39.048294     10.047818     29.913395   
std       58.752005     29.629011     27.437827      7.773112     19.314587   
min        7.000000      0.000000      0.000000      0.000000      1.000000   
25%       39.000000     20.000000     19.000000      4.000000     15.000000   
50%       59.000000     31.000000     28.000000      7.000000     24.000000   
75%      118.000000     62.000000     57.000000     14.000000     40.000000   
max      271.000000    152.000000    145.000000     48.000000    125.000000   

                IBB           HBP            WP            BK            SO  \
count  10519.000000  10519.000000  10519.000000  10519.000000  10519.000000   
mean       2.151630      3.312007      3.096112      0.291473     68.996958   
std        2.086209      3.005256      2.840299      0.619634     49.658313   
min        0.000000      0.000000      0.000000      0.000000      4.000000   
25%        1.000000      1.000000      1.000000      0.000000     32.000000   
50%        2.000000      3.000000      2.000000      0.000000     54.000000   
75%        3.000000      5.000000      4.000000      0.000000     90.000000   
max       17.000000     24.000000     25.000000      6.000000    372.000000   

                GB           FB           LD         IFFB        Balls  \
count  9638.000000  9638.000000  9638.000000  9638.000000  9638.000000   
mean    109.963893    88.565678    50.812202     9.064640   499.914920   
std      82.919192    64.477807    37.016805     7.723648   329.168027   
min       6.000000     7.000000     1.000000     0.000000    86.000000   
25%      49.000000    41.000000    24.000000     4.000000   255.000000   
50%      80.000000  

## bWAR Pitching 

Get Baseball Reference's WAR stats from its war_daily_pitch table, along with some other data that's not included in the pitching_stats_bref function. 

For the purposes of this project, we will care about salary, WAR, and the above average columns. We can later merge this dataframe with the `pitching_2022` dataframe.

In [461]:
from pybaseball import bwar_pitch

# get war stats from baseball reference 
bwar_pitch = bwar_pitch(return_all = True)
bwar_pitch.head()

name_common   age    mlb_ID  player_ID  year_ID team_ID  stint_ID lg_ID  \
0  David Aardsma  22.0  430911.0  aardsda01     2004     SFG         1    NL   
1  David Aardsma  24.0  430911.0  aardsda01     2006     CHC         1    NL   
2  David Aardsma  25.0  430911.0  aardsda01     2007     CHW         1    AL   
3  David Aardsma  26.0  430911.0  aardsda01     2008     BOS         1    AL   
4  David Aardsma  27.0  430911.0  aardsda01     2009     SEA         1    AL   

    G  GS  IPouts  IPouts_start  IPouts_relief  RA     xRA  xRA_sprp_adj  \
0  11   0      32           0.0           32.0   8   5.967        -0.440   
1  45   0     159           0.0          159.0  25  28.172        -2.076   
2  25   0      97           0.0           97.0  24  17.999        -1.343   
3  47   0     146           0.0          146.0  32  26.131        -1.942   
4  73   0     214           0.0          214.0  23  39.221        -2.895   

   xRA_extras_adj  xRA_def_pitcher  PPF  PPF_custom  xRA_final    BIP  \
0             NaN           -0.423  101      98.525      5.862   44.0   
1             NaN           -0.367  103     104.018     27.526  147.0   
2             NaN           -1.327  104     103.205     18.559   97.0   
3             NaN            0.663  106     106.614     25.082  139.0   
4             NaN            3.136   95      93.595     31.064  181.0   

   BIP_perc  RS_def_total  runs_above_avg  runs_above_avg_adj  runs_above_rep  \
0    0.0093         -45.5          -2.138              -2.177          -1.199   
1    0.0337         -10.9           2.526               2.751           7.388   
2    0.0206         -64.4          -5.441              -5.646          -1.814   
3    0.0317          20.9          -6.918              -7.757          -1.633   
4    0.0399          78.6           8.064               7.689          15.965   

   RpO_replacement  GR_leverage_index_avg   WAR    salary  teamRpG   oppRpG  \
0            0.203                 1.0718 -0.15  300000.0  4.67092  4.86883   
1            0.211                 0.7542  0.61       NaN  4.86675  4.80561   
2            0.218                 1.4280 -0.40  387500.0  4.85895  5.08479   
3            0.211                 0.7972 -0.31  403250.0  4.70400  4.86905   
4            0.215                 1.8922  1.69  419000.0  4.79788  4.69256   

   pyth_exponent  waa_win_perc     WAA  WAA_adj  oppRpG_rep  \
0          1.902        0.4803 -0.2167  -0.0298     4.75633   
1          1.909        0.5060  0.2700  -0.1301     4.97303   
2          1.924        0.4782 -0.5450  -0.1990     5.00394   
3          1.904        0.4836 -0.7708  -0.0632     4.81624   
4          1.899        0.5105  0.7665   0.1577     4.90529   

   pyth_exponent_rep  waa_win_perc_rep  WAR_rep    ERA_plus   ER_lg  
0              1.895            0.4914   0.0942   66.675000   5.334  
1              1.919            0.4896   0.4682  114.295833  27.431  
2              1.920            0.4859   0.3459   74.086957  17.040  
3              1.901            0.4888   0.5205   83.796667  25.139  
4              1.911            0.4894   0.7666  168.910000  33.782

In [462]:
# load in csv
bwar_pitch = pd.read_csv('Data/bwar_pitch', index_col = 0)

In [463]:
# filter bwar_bat to 2000 - 2021
bwar_pitch_2021 = bwar_pitch[(bwar_pitch['year_ID'].between(2000, 2021))]
bwar_pitch_2021.sort_values(by = 'year_ID')

name_common   age    mlb_ID  player_ID  year_ID team_ID  \
48453        Ismael Valdez  26.0  123595.0  valdeis01     2000     LAD   
36746           Brad Penny  22.0  207267.0  pennybr01     2000     FLA   
15902          Aaron Fultz  26.0  150269.0  fultzaa01     2000     SFG   
36671           Jesus Pena  25.0  227494.0   penaje01     2000     CHW   
36670           Jesus Pena  25.0  227494.0   penaje01     2000     BOS   
...                    ...   ...       ...        ...      ...     ...   
16240          Luis Garcia  24.0  677651.0  garcilu05     2021     HOU   
2190            Joe Barlow  25.0  669618.0  barlojo01     2021     TEX   
34785         Darien Núñez  28.0  628345.0  nunezda01     2021     LAD   
31583  Julian Merryweather  29.0  657240.0  merryju01     2021     TOR   
32901         Jovani Moran  24.0  663558.0  moranjo01     2021     MIN   

       stint_ID lg_ID   G  GS  IPouts  IPouts_start  IPouts_relief  RA  \
48453         2    NL   9   8     120         113.0            7.0  29   
36746         1    NL  23  22     359         348.0           11.0  70   
15902         1    NL  58   0     208           0.0          208.0  38   
36671         1    AL  20   0      70           0.0           70.0  18   
36670         2    AL   2   0       9           0.0            9.0   1   
...         ...   ...  ..  ..     ...           ...            ...  ..   
16240         1    AL  30  28     466         448.0           18.0  62   
2190          1    AL  31   0      87           0.0           87.0   9   
34785         1    NL   6   1      23           0.0           23.0   8   
31583         1    AL  13   1      39           3.0           36.0   7   
32901         1    AL   5   0      24           0.0           24.0   7   

          xRA  xRA_sprp_adj  xRA_extras_adj  xRA_def_pitcher  PPF  PPF_custom  \
48453  21.189         0.622             NaN            0.193   93      90.888   
36746  65.451         2.124             NaN           -0.977   95      95.346   
15902  39.600        -3.033             NaN            0.259   92      95.699   
36671  13.931        -1.031             NaN            0.088  102     103.505   
36670   1.685        -0.125             NaN            0.082  103     102.143   
...       ...           ...             ...              ...  ...         ...   
16240  80.240         3.471           0.000            7.563   99      98.900   
2190   15.034        -0.976           1.252            1.579  101     100.216   
34785   3.851        -0.251           0.000            0.226   97      96.424   
31583   6.608        -0.372           1.256            0.233  101      99.673   
32901   4.209        -0.273           0.000            0.190   98     100.474   

       xRA_final    BIP  BIP_perc  RS_def_total  runs_above_avg  \
48453     19.648  135.0    0.0306           6.3          -9.352   
36746     65.362  384.0    0.0842         -11.6          -4.638   
15902     34.746  206.0    0.0455           5.7          -3.254   
36671     13.261   73.0    0.0158           5.6          -4.739   
36670      1.510   10.0    0.0022          37.3           0.510   
...          ...    ...       ...           ...             ...   
16240     75.310  413.0    0.1036          73.0          13.310   
2190      13.761   72.0    0.0168          94.0           4.761   
34785      3.253   21.0    0.0055          41.0          -4.747   
31583      7.235   38.0    0.0097          24.0           0.235   
32901      3.764   21.0    0.0050          38.0          -3.236   

       runs_above_avg_adj  runs_above_rep  RpO_replacement  \
48453              -9.470          -5.544            0.219   
36746              -4.992           6.753            0.219   
15902              -3.459           3.346            0.219   
36671              -4.915          -1.874            0.239   
36670               0.487           0.878            0.239   
...                   ...             ...              ...   
16240              12.334

In [464]:
bwar_pitch_2021.describe()

age         mlb_ID       year_ID      stint_ID             G  \
count  16555.000000   16555.000000  16555.000000  16555.000000  16555.000000   
mean      28.208819  420390.276170   2011.200725      1.091755     24.818665   
std        4.092570  169844.593075      6.424128      0.303380     20.692657   
min       19.000000  110015.000000   2000.000000      1.000000      0.000000   
25%       25.000000  339492.000000   2006.000000      1.000000      8.000000   
50%       28.000000  452291.000000   2012.000000      1.000000     20.000000   
75%       31.000000  543488.000000   2017.000000      1.000000     34.000000   
max       49.000000  685503.000000   2021.000000      5.000000     94.000000   

                 GS        IPouts  IPouts_start  IPouts_relief            RA  \
count  16555.000000  16555.000000  16520.000000   16520.000000  16555.000000   
mean       6.271821    167.713259    108.986864      59.081719     28.677439   
std       10.366798    173.009266    188.530744      69.330749     28.686131   
min        0.000000      0.000000      0.000000     -15.000000      0.000000   
25%        0.000000     38.000000      0.000000       3.000000      8.000000   
50%        0.000000    110.000000      0.000000      28.000000     19.000000   
75%        9.000000    218.000000    136.000000      96.000000     37.000000   
max       36.000000    798.000000    798.000000     316.000000    152.000000   

                xRA  xRA_sprp_adj  xRA_extras_adj  xRA_def_pitcher  \
count  16555.000000  16555.000000     1808.000000     16555.000000   
mean      28.863240     -0.008486        0.297436         0.129360   
std       29.714675      1.805132        0.650680         2.155056   
min        0.000000     -4.400000        0.000000       -15.587000   
25%        6.618500     -1.107000        0.000000        -0.432000   
50%       18.981000     -0.226000        0.000000         0.028000   
75%       37.784000      0.678000        0.000000         0.617500   
max      145.076000      5.806000        5.611000        16.916000   

                PPF    PPF_custom     xRA_final           BIP      BIP_perc  \
count  16555.000000  16520.000000  16555.000000  16555.000000  16555.000000   
mean     100.080882    100.381012     28.792937    171.880519      0.039867   
std        5.036742      5.904402     30.839335    179.299934      0.040367   
min       88.000000     76.000000      0.000000      0.000000      0.000000   
25%       97.000000     96.800000      6.308000     40.000000      0.009700   
50%      100.000000    100.000000     18.286000    111.000000      0.026700   
75%      103.000000    103.068000     36.628000    220.000000      0.050700   
max      125.000000    150.000000    162.764000    826.000000      0.180800   

       RS_def_total  runs_above_avg  runs_above_avg_adj  runs_above_rep  \
count  16555.000000    16555.000000        16555.000000    16555.000000   
mean       2.601963        0.115498            0.000002        5.479490   
std       38.258688        9.936283            9.887849       13.078215   
min     -115.200000      -43.678000          -44.187000      -35.371000   
25%      -24.000000       -4.821000           -4.893500       -2.082000   
50%        3.000000       -0.661000           -0.710000        1.846000   
75%       27.300000        3.572000            3.489000        9.413500   
max      116.000000       93.600000           91.966000      120.240000   

       RpO_replacement  GR_leverage_index_avg           WAR        salary  \
count     16555.000000           16555.000000  16520.000000  8.854000e+03   
mean          0.203146               0.902624      0.530495  3.114571e+06   
std           0.013243               0.476755      1.309606  4.556342e+06   
min           0.175000               0.000000     -2.760000  1.000000e+05   
25%           0.195000               0.600000     -0.200000  4.935000e+05   
50%           0.203000               1.000000      0.120000  1.050000e+06   
75%           0.

In [465]:
# how many missing values in pitching salary column?
print("Missing bWAR Pitching Salary Data:")
bwar_pitch_2021['salary'].isna().value_counts(normalize = True)

Missing bWAR Pitching Salary Data:


False    0.534823
True     0.465177
Name: salary, dtype: float64

## Formatting the Batting Table

**Join `batting_2021` with `bwar_bat_2021` on the following columns:**

**`batting_2021`** 
- `Name`
- `Season`

**`bwar_bat_2021`**  
- `name_common`
- `year_ID`

In [466]:
# join batting_2021 onto bwar_bat_2021 (left join)
batting_merged = pd.merge(bwar_bat_2021, batting_2021, how='left',left_on=['name_common','year_ID'],right_on=['Name','Season'])

In [467]:
batting_merged.head(10)

name_common    mlb_ID  player_ID  year_ID team_ID  stint_ID lg_ID  \
0         Jeff Abbott  110010.0  abbotje01     2000     CHW         1    AL   
1         Kurt Abbott  110011.0  abbotku01     2000     NYM         1    NL   
2  Reggie Abercrombie  430631.0  abercre01     2006     FLA         1    NL   
3  Reggie Abercrombie  430631.0  abercre01     2007     FLA         1    NL   
4  Reggie Abercrombie  430631.0  abercre01     2008     HOU         1    NL   
5     Brent Abernathy  150466.0  abernbr01     2001     TBD         1    AL   
6     Brent Abernathy  150466.0  abernbr01     2002     TBD         1    AL   
7     Brent Abernathy  150466.0  abernbr01     2005     MIN         1    AL   
8         Bobby Abreu  110029.0  abreubo01     2000     PHI         1    NL   
9         Bobby Abreu  110029.0  abreubo01     2001     PHI         1    NL   

  pitcher  G_x   PA_x     salary  runs_above_avg  runs_above_avg_off  \
0       N   80  242.0   255000.0           -12.6                -6.7   
1       N   79  173.0   500000.0            -9.1                -6.8   
2       N  111  281.0   327000.0           -15.6               -11.6   
3       N   35   80.0        NaN            -1.1                -4.1   
4       N   34   60.0        NaN             2.6                 1.6   
5       N   79  335.0        NaN            -0.6                 0.4   
6       N  117  504.0   215000.0           -19.8               -18.5   
7       N   24   79.0        NaN            -4.4                -3.4   
8       N  154  680.0  2933333.0            45.9                31.2   
9       N  162  704.0  4983000.0            33.2                32.2   

   runs_above_avg_def  WAR_rep   WAA  WAR_x       IDfg  Season  \
0                -7.3     0.84 -1.13  -0.29  1000011.0  2000.0   
1                 0.6     0.52 -0.93  -0.41  1000013.0  2000.0   
2                -3.1     0.84 -1.58  -0.74     2187.0  2006.0   
3                 3.2     0.24 -0.12   0.12     2187.0  2007.0   
4                 0.7     0.18  0.24   0.42     2187.0  2008.0   
5                 1.1     1.21 -0.02   1.19     1192.0  2001.0   
6                 1.8     1.77 -1.95  -0.18     1192.0  2002.0   
7                -1.0     0.28 -0.44  -0.16     1192.0  2005.0   
8                 8.9     2.02  4.16   6.18      945.0  2000.0   
9                -5.1     2.10  3.09   5.19      945.0  2001.0   

                 Name Team   Age    G_y     AB   PA_y      H     1B    2B  \
0         Jeff Abbott  CHW  27.0   80.0  215.0  242.0   59.0   40.0  15.0   
1         Kurt Abbott  NYM  31.0   79.0  157.0  173.0   34.0   20.0   7.0   
2  Reggie Abercrombie  FLA  24.0  111.0  255.0  281.0   54.0   35.0  12.0   
3  Reggie Abercrombie  FLA  25.0   35.0   76.0   80.0   15.0   10.0   3.0   
4  Reggie Abercrombie  HOU  26.0   34.0   55.0   60.0   17.0   10.0   5.0   
5     Brent Abernathy  TBD  23.0   79.0  304.0  335.0   82.0   59.0  17.0   
6     Brent Abernathy  TBD  24.0  117.0  463.0  504.0  112.0   88.0  18.0   
7     Brent Abernathy  MIN  27.0   24.0   67.0   79.0   16.0   14.0   1.0   
8         Bobby Abreu  PHI  26.0  154.0  576.0  680.0  182.0  105.0  42.0   
9         Bobby Abreu  PHI  27.0  162.0  588.0  704.0  170.0   87.0  48.0   

     3B    HR      R    RBI     BB   IBB     SO  HBP   SF   SH   GDP    SB  \
0   1.0   3.0   31.0   29.0   21.0   1.0   38.0  2.0  1.0  2.0   2.0   2.0   
1   1.0   6.0   22.0   12.0   14.0   2.0   51.0  1.0  1.0  0.0   2.0   1.0   
2   2.0   5.0   39.0   24.0   18.0   2.0   78.0  3.0  1.0  4.0   2.0   6.0   
3   0.0   2.0   16.0    5.0    2.0   0.0   22.0  2.0  0.0  0.0   1.0   7.0   
4   0.0   2.0   10.0    5.0    1.0   0.0   23.0  2.0  1.0  1.0   0.0   5.0   
5   1.0   5.0   43.0   33.0   27.0   1.0   35.0  0.0  1.0  3.0   3.0   8.0   
6   4.0   2.0   46.0   40.0   25.0   0.0   46.0  6.0  2.0  8.0   8.0  10.0   
7   0.0   1.0    5.0    6.0    7.0   0.0    9.0  1.0  1.0  3.0   2.0   2.0   
8  10.0  25.0  103.0   79.0  100.0   9.0  116.0  1.0  3.0  0.0  12.0  

**Filling missing `salary` values.**

We have missing salary values for approximately 25% of batters in the `batting_merged` dataset. Most of the missing values are likely due to clerical input whereby a player's salary for future years may not be filled in, but may be accounted for in an earlier year. 

For example, take a look at the player Reggie Abercrombie in the 2006 season. His 2006 salary is available, however, 2007 season is not. And in 2008, Reggie changed teams and his salary is still missing. Similarly, we see missing values for Brent Abernathy, whereby his 2001 and 2005 seasons contain missing salary data but his salary is available in the 2002 season. 

There are also players who were traded mid-season. The player is accounted for twice for a single season because they played for a different team and the salary may be missing for one of the entries. However, we will treat their salaries as the same for both teams. 

To fill in these missing values, we will assume the following:
- A player's salary is the same across consecutive seasons even if the salary is missing
- Players traded mid-season will have the same salary for that season across both teams


In [468]:
# make a copy and specify which column to fill missing values
salary_col = ['salary']
batting_filled = batting_merged.copy()

In [469]:
# forward and backward fills missing values grouped by name
batting_filled.loc[:,salary_col] = batting_merged.loc[:,salary_col].groupby(batting_filled['name_common']).ffill().bfill()

In [470]:
# check
batting_filled.tail(10)

name_common    mlb_ID  player_ID  year_ID team_ID  stint_ID lg_ID  \
12644  Julio Zuleta  275936.0  zuletju01     2001     CHC         1    NL   
12645   Mike Zunino  572287.0  zuninmi01     2013     SEA         1    AL   
12646   Mike Zunino  572287.0  zuninmi01     2014     SEA         1    AL   
12647   Mike Zunino  572287.0  zuninmi01     2015     SEA         1    AL   
12648   Mike Zunino  572287.0  zuninmi01     2016     SEA         1    AL   
12649   Mike Zunino  572287.0  zuninmi01     2017     SEA         1    AL   
12650   Mike Zunino  572287.0  zuninmi01     2018     SEA         1    AL   
12651   Mike Zunino  572287.0  zuninmi01     2019     TBR         1    AL   
12652   Mike Zunino  572287.0  zuninmi01     2020     TBR         1    AL   
12653   Mike Zunino  572287.0  zuninmi01     2021     TBR         1    AL   

      pitcher  G_x   PA_x     salary  runs_above_avg  runs_above_avg_off  \
12644       N   49  118.0   200000.0            -6.7                -5.4   
12645       N   52  193.0   504100.0            -3.6                 0.4   
12646       N  131  476.0   504100.0           -12.7                -4.7   
12647       N  112  386.0   523500.0           -19.9               -18.9   
12648       N   55  192.0   523500.0            10.2                 6.2   
12649       N  124  435.0   570000.0            18.6                17.6   
12650       N  113  405.0  2975000.0             2.9                -4.1   
12651       N   90  289.0  4412000.0           -13.0               -17.0   
12652       N   28   84.0  4500000.0            -3.3                -2.3   
12653       N  109  375.0  2000000.0            24.5                25.5   

       runs_above_avg_def  WAR_rep   WAA  WAR_x       IDfg  Season  \
12644                -2.6     0.35 -0.71  -0.36  1014462.0  2001.0   
12645                -0.8     0.66 -0.31   0.35    13265.0  2013.0   
12646                 0.3     1.65 -1.23   0.42    13265.0  2014.0   
12647                 5.9     1.35 -2.05  -0.70    13265.0  2015.0   
12648                 7.2     0.67  1.10   1.77    13265.0  2016.0   
12649                 8.3     1.51  1.91   3.42    13265.0  2017.0   
12650                13.9     1.38  0.49   1.87    13265.0  2018.0   
12651                 9.1     0.98 -1.18  -0.20    13265.0  2019.0   
12652                 0.7     0.28 -0.34  -0.06    13265.0  2020.0   
12653                 5.4     1.25  2.50   3.75    13265.0  2021.0   

               Name Team   Age    G_y     AB   PA_y     H    1B    2B   3B  \
12644  Julio Zuleta  CHC  26.0   49.0  106.0  118.0  23.0  14.0   3.0  0.0   
12645   Mike Zunino  SEA  22.0   52.0  173.0  193.0  37.0  27.0   5.0  0.0   
12646   Mike Zunino  SEA  23.0  131.0  438.0  476.0  87.0  43.0  20.0  2.0   
12647   Mike Zunino  SEA  24.0  112.0  350.0  386.0  61.0  39.0  11.0  0.0   
12648   Mike Zunino  SEA  25.0   55.0  164.0  192.0  34.0  15.0   7.0  0.0   
12649   Mike Zunino  SEA  26.0  124.0  387.0  435.0  97.0  47.0  25.0  0.0   
12650   Mike Zunino  SEA  27.0  113.0  373.0  405.0  75.0  37.0  18.0  0.0   
12651   Mike Zunino  TBR  28.0   90.0  266.0  289.0  44.0  24.0  10.0  1.0   
12652   Mike Zunino  TBR  29.0   28.0   75.0   84.0  11.0   3.0   4.0  0.0   
12653   Mike Zunino  TBR  30.0  109.0  333.0  375.0  72.0  26.0  11.0  2.0   

         HR     R   RBI    BB  IBB     SO   HBP   SF   SH   GDP   SB   CS  \
12644   6.0  11.0  24.0   8.0  1.0   32.0   3.0  1.0  0.0   3.0  0.0  1.0   
12645   5.0  22.0  14.0  16.0  0.0   49.0   3.0  1.0  0.0   5.0  1.0  0.0   
12646  22.0  51.0  60.0  17.0  1.0  158.0  17.0  4.0  0.0  13.0  0.0  3.0   
12647  11.0  28.0  28.0  21.0  0.0  132.0   5.0  2.0  8.0   6.0  0.0  1.0   
12648  12.0  16.0  31.0  21.0  0.0   65.0   6.0  1.0  0.0   0.0  0.0  0.0   
12649  25.0  52.0  64.0  39.0  0.0  160.0   8.0  1.0  0.0   8.0  1.0  0.0   
12650  20.0  37.0  44.0  24.0  0.0  150.0   6.0  2.0  0.0   7.0  0.0  0.0   
12651   9.0  30.0  32.0  20.0  0.0   98.0   3.0  0.0  0.0   4.0  0.0  0.0   


In [471]:
# check
batting_filled.salary.isna().sum()

0

In [472]:
batting_filled.describe()

mlb_ID       year_ID      stint_ID           G_x          PA_x  \
count   12654.000000  12654.000000  12654.000000  12654.000000  12654.000000   
mean   378158.934408   2010.372768      1.071124     84.800142    305.191797   
std    180648.402908      6.299129      0.269059     45.604587    206.956811   
min    110010.000000   2000.000000      1.000000     12.000000     50.000000   
25%    150134.000000   2005.000000      1.000000     41.000000    115.000000   
50%    430948.000000   2010.000000      1.000000     81.000000    253.000000   
75%    506702.000000   2016.000000      1.000000    128.000000    482.000000   
max    683734.000000   2021.000000      4.000000    163.000000    778.000000   

             salary  runs_above_avg  runs_above_avg_off  runs_above_avg_def  \
count  1.265400e+04    12654.000000        12654.000000        12654.000000   
mean   3.514898e+06        0.549075            0.543931            0.006235   
std    5.031192e+06       13.827548           12.047300            7.623109   
min    1.000000e+00      -50.400000          -42.400000          -50.700000   
25%    4.865000e+05       -7.300000           -6.300000           -3.700000   
50%    1.000000e+06       -1.700000           -1.600000            0.100000   
75%    4.696875e+06        5.100000            4.400000            3.300000   
max    3.833333e+07      106.300000          110.900000           49.300000   

            WAR_rep           WAA         WAR_x          IDfg        Season  \
count  12654.000000  12654.000000  12654.000000  1.234000e+04  12340.000000   
mean       0.982177      0.041925      1.024102  2.104155e+04   2010.365316   
std        0.700223      1.398348      1.774528  1.253181e+05      6.288774   
min        0.000000     -5.040000     -3.250000  1.000000e+00   2000.000000   
25%        0.380000     -0.750000     -0.140000  1.004000e+03   2005.000000   
50%        0.820000     -0.170000      0.460000  3.204500e+03   2010.000000   
75%        1.580000      0.510000      1.720000  8.709000e+03   2016.000000   
max        2.520000      9.880000     11.850000  1.014462e+06   2021.000000   

                Age           G_y            AB          PA_y             H  \
count  12340.000000  12340.000000  12340.000000  12340.000000  12340.000000   
mean      28.709643     91.549838    292.670502    328.128849     76.409157   
std        4.144746     44.882189    184.780996    207.649123     54.294969   
min       19.000000     12.000000     36.000000     50.000000      1.000000   
25%       26.000000     48.000000    122.000000    135.000000     28.000000   
50%       28.000000     94.000000    264.000000    294.000000     65.000000   
75%       31.000000    134.000000    460.000000    514.000000    121.000000   
max       48.000000    163.000000    716.000000    778.000000    262.000000   

                 1B            2B            3B            HR             R  \
count  12340.000000  12340.000000  12340.000000  12340.000000  12340.000000   
mean      50.149028     15.277472      1.564425      9.418233     39.513371   
std       35.889682     11.719567      2.108488      9.786556     30.119826   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%       18.000000      5.000000      0.000000      2.000000     14.000000   
50%       43.000000     13.000000      1.000000      6.000000     32.000000   
75%       78.000000     24.000000      2.000000     14.000000     61.000000   
max      225.000000     59.000000     23.000000     73.000000    152.000000   

                RBI            BB           IBB            SO           HBP  \
count  12340.000000  12340.000000  12340.000000  12340.000000  12340.000000   
mean      37.795462     28.041653      2.024068     61.168882      3.076418   
std       30.385043     23.590288      3.615751     39.147186      3.564589   
min        0.000000      0.000000      0.000000      2.000000      0.000000   
25%       12.000000      9.000000      0.000000   

## Simplify and separate the `batting_filled` table

Because there are so many advanced statistics available in the dataframe, we can reduce the number of columns down to standard team statistics that do not include StatCast data. 

As mentioned earlier, StatCast was first introduced to MLB in 2014 and was not fully installed at every ballpark until 2015. Therfore, there will be many missing values for the advanced StatCast features. 

Thus, we will create two separate batting tables:
- `batting_basic` (containing basic data between 2000 - 2021)
- `batting_adv` (containing basic AND StatCast data between 2014 - 2021)

We'll also remove repetitive columns that we brought in during the initial merge of tables. 

In [473]:
batting_filled.head(1)

name_common    mlb_ID  player_ID  year_ID team_ID  stint_ID lg_ID pitcher  \
0  Jeff Abbott  110010.0  abbotje01     2000     CHW         1    AL       N   

   G_x   PA_x    salary  runs_above_avg  runs_above_avg_off  \
0   80  242.0  255000.0           -12.6                -6.7   

   runs_above_avg_def  WAR_rep   WAA  WAR_x       IDfg  Season         Name  \
0                -7.3     0.84 -1.13  -0.29  1000011.0  2000.0  Jeff Abbott   

  Team   Age   G_y     AB   PA_y     H    1B    2B   3B   HR     R   RBI  \
0  CHW  27.0  80.0  215.0  242.0  59.0  40.0  15.0  1.0  3.0  31.0  29.0   

     BB  IBB    SO  HBP   SF   SH  GDP   SB   CS    AVG  GB  FB  LD  IFFB  \
0  21.0  1.0  38.0  2.0  1.0  2.0  2.0  2.0  1.0  0.274 NaN NaN NaN   NaN   

   Pitches  Balls  Strikes  IFH  BU  BUH    BB%     K%  BB/K    OBP    SLG  \
0      NaN    NaN      NaN  NaN NaN  NaN  0.087  0.157  0.55  0.343  0.395   

     OPS    ISO  BABIP  GB/FB  LD%  GB%  FB%  IFFB%  HR/FB  IFH%  BUH%   wOBA  \
0  0.738  0.121   0.32    NaN  NaN  NaN  NaN    NaN    NaN   NaN   NaN  0.328   

   wRAA   wRC  Bat  Fld  Rep  Pos  RAR  WAR_y  Dol  Spd  wRC+   WPA  -WPA  \
0  -2.7  29.0 -4.2 -5.0  7.8 -1.6 -2.1   -0.2  NaN  3.9  87.0  0.37 -3.89   

   +WPA  RE24   REW  pLI  phLI    PH  WPA/LI  Clutch  FB% (Pitch)  FBv  SL%  \
0  4.26 -6.74 -0.57  0.9  1.79  14.0   -0.16    0.57          NaN  NaN  NaN   

   SLv  CT%  CTv  CB%  CBv  CH%  CHv  SF%  SFv  KN%  KNv  XX%  PO%  wFB  wSL  \
0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

   wCT  wCB  wCH  wSF  wKN  wFB/C  wSL/C  wCT/C  wCB/C  wCH/C  wSF/C  wKN/C  \
0  NaN  NaN  NaN  NaN  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   

   O-Swing%  Z-Swing%  Swing%  O-Contact%  Z-Contact%  Contact%  Zone%  \
0       NaN       NaN     NaN         NaN         NaN       NaN    NaN   

   F-Strike%  SwStr%  BsR  FA% (sc)  FT% (sc)  FC% (sc)  FS% (sc)  FO% (sc)  \
0        NaN     NaN  0.0       NaN       NaN       NaN       NaN       NaN   

   SI% (sc)  SL% (sc)  CU% (sc)  KC% (sc)  EP% (sc)  CH% (sc)  SC% (sc)  \
0       NaN       NaN       NaN       NaN       NaN       NaN       NaN   

   KN% (sc)  UN% (sc)  vFA (sc)  vFT (sc)  vFC (sc)  vFS (sc)  vFO (sc)  \
0       NaN       NaN       NaN       NaN       NaN       NaN       NaN   

   vSI (sc)  vSL (sc)  vCU (sc)  vKC (sc)  vEP (sc)  vCH (sc)  vSC (sc)  \
0       NaN       NaN       NaN       NaN       NaN       NaN       NaN   

   vKN (sc)  FA-X (sc)  FT-X (sc)  FC-X (sc)  FS-X (sc)  FO-X (sc)  SI-X (sc)  \
0       NaN        NaN        NaN        NaN        NaN        NaN        NaN   

   SL-X (sc)  CU-X (sc)  KC-X (sc)  EP-X (sc)  CH-X (sc)  SC-X (sc)  \
0        NaN        NaN        NaN        NaN        NaN        NaN   

   KN-X (sc)  FA-Z (sc)  FT-Z (sc)  FC-Z (sc)  FS-Z (sc)  FO-Z (sc)  \
0        NaN        NaN        NaN        NaN        NaN        NaN   

   SI-Z (sc)  SL-Z (sc)  CU-Z (sc)  KC-Z (sc)  EP-Z (sc)  CH-Z (sc)  \
0        NaN        NaN        NaN        NaN        NaN        NaN   

   SC-Z (sc)  KN-Z (sc)  wFA (sc)  wFT (sc)  wFC (sc)  wFS (sc)  wFO (sc)  \
0        NaN        NaN       NaN       NaN       NaN       NaN       NaN   

   wSI (sc)  wSL (sc)  wCU (sc)  wKC (sc)  wEP (sc)  wCH (sc)  wSC (sc)  \
0       NaN       NaN       NaN       NaN       NaN       NaN       NaN   

   wKN (sc)  wFA/C (sc)  wFT/C (sc)  wFC/C (sc)  wFS/C (sc)  wFO/C (sc)  \
0       NaN         NaN         NaN         NaN         NaN         NaN   

   wSI/C (sc)  wSL/C (sc)  wCU/C (sc)  wKC/C (sc)  wEP/C (sc)  wCH/C (sc)  \
0         NaN         NaN         NaN         NaN         NaN         NaN   

   wSC/C (sc)  wKN/C (sc)  O-Swing% (sc)  Z-Swing% (sc)  Swing% (sc)  \
0         NaN         NaN            NaN            NaN          NaN   

   O-Contact% (sc)  Z-Contact% (sc)  Contact% (sc)  Zone% (sc)  Pace  Def  \
0              NaN              NaN            NaN         NaN   NaN -6.6   

   wSB  UBR  Age Rng  Off   L

In [474]:
# get all column names
with pd.option_context('display.max_seq_items', None):
    print (batting_filled.columns)

Index(['name_common', 'mlb_ID', 'player_ID', 'year_ID', 'team_ID', 'stint_ID',
       'lg_ID', 'pitcher', 'G_x', 'PA_x', 'salary', 'runs_above_avg',
       'runs_above_avg_off', 'runs_above_avg_def', 'WAR_rep', 'WAA', 'WAR_x',
       'IDfg', 'Season', 'Name', 'Team', 'Age', 'G_y', 'AB', 'PA_y', 'H', '1B',
       '2B', '3B', 'HR', 'R', 'RBI', 'BB', 'IBB', 'SO', 'HBP', 'SF', 'SH',
       'GDP', 'SB', 'CS', 'AVG', 'GB', 'FB', 'LD', 'IFFB', 'Pitches', 'Balls',
       'Strikes', 'IFH', 'BU', 'BUH', 'BB%', 'K%', 'BB/K', 'OBP', 'SLG', 'OPS',
       'ISO', 'BABIP', 'GB/FB', 'LD%', 'GB%', 'FB%', 'IFFB%', 'HR/FB', 'IFH%',
       'BUH%', 'wOBA', 'wRAA', 'wRC', 'Bat', 'Fld', 'Rep', 'Pos', 'RAR',
       'WAR_y', 'Dol', 'Spd', 'wRC+', 'WPA', '-WPA', '+WPA', 'RE24', 'REW',
       'pLI', 'phLI', 'PH', 'WPA/LI', 'Clutch', 'FB% (Pitch)', 'FBv', 'SL%',
       'SLv', 'CT%', 'CTv', 'CB%', 'CBv', 'CH%', 'CHv', 'SF%', 'SFv', 'KN%',
       'KNv', 'XX%', 'PO%', 'wFB', 'wSL', 'wCT', 'wCB', 'wCH', 'wSF', 'wKN',


**Specify columns for `batting_basic`**

In [475]:
# basic batting columns to keep
batting_basic_columns = ['name_common', 'player_ID', 'year_ID', 'team_ID', 'lg_ID',
                         'salary', 'Age', 'G_y', 'AB', 'PA_y', 'AVG', 'H', '1B', '2B', '3B', 
                         'HR', 'R', 'RBI', 'BB', 'IBB', 'SO', 'HBP', 'SF', 'SH', 'GDP', 'SB', 
                         'CS', 'BB%', 'K%', 'BB/K', 'OBP', 'SLG', 'OPS', 'ISO', 'BABIP']

# create new batting_basic table with specified columns i want
batting_basic = batting_filled[batting_basic_columns]

# renaming columns
batting_basic = batting_basic.rename(columns = {'name_common':'name',
                                                'G_y':'G',
                                                'PA_y':'PA'})

**Specify columns for `batting_adv`**

In [476]:
# adv batting columns to keep
batting_adv_columns = ['name_common', 'player_ID', 'year_ID', 'team_ID', 'lg_ID',
                           'salary', 'Age', 'G_y', 'AB', 'PA_y', 'AVG', 'H', '1B', '2B', '3B', 
                           'HR', 'R', 'RBI', 'BB', 'IBB', 'SO', 'HBP', 'SF', 'SH', 'GDP', 'SB', 
                           'CS', 'BB%', 'K%', 'BB/K', 'OBP', 'SLG', 'OPS', 'ISO', 'BABIP',
                           'runs_above_avg', 'runs_above_avg_off', 'runs_above_avg_def', 
                           'WAR_rep', 'WAA', 'WAR_x', 'GB', 'FB', 'LD', 'IFFB', 'Pitches', 
                           'Balls', 'Strikes', 'IFH', 'BU', 'BUH', 'BB%', 'K%', 'BB/K', 'OBP', 
                           'SLG', 'OPS', 'ISO', 'BABIP', 'GB/FB', 'LD%', 'GB%', 'FB%', 'IFFB%', 
                           'HR/FB', 'IFH%', 'BUH%', 'wOBA', 'wRAA', 'wRC', 'Bat', 'Fld', 'Rep', 
                           'Pos', 'RAR', 'Spd', 'wRC+', 'WPA', '-WPA', '+WPA', 'RE24', 'REW',
                           'pLI', 'phLI', 'PH', 'WPA/LI', 'Clutch', 'FB% (Pitch)', 'FBv', 'SL%',
                           'SLv', 'CT%', 'CTv', 'CB%', 'CBv', 'CH%', 'CHv', 'SF%', 'SFv', 'KN%',
                           'KNv', 'XX%', 'PO%', 'wFB', 'wSL', 'wCT', 'wCB', 'wCH', 'wSF', 'wKN',
                           'wFB/C', 'wSL/C', 'wCT/C', 'wCB/C', 'wCH/C', 'wSF/C', 'wKN/C',
                           'O-Swing%', 'Z-Swing%', 'Swing%', 'O-Contact%', 'Z-Contact%',
                           'Contact%', 'Zone%', 'F-Strike%', 'SwStr%', 'BsR', 'FA% (sc)',
                           'FT% (sc)', 'FC% (sc)', 'FS% (sc)', 'FO% (sc)', 'SI% (sc)', 'SL% (sc)',
                           'CU% (sc)', 'KC% (sc)', 'EP% (sc)', 'CH% (sc)', 'SC% (sc)', 'KN% (sc)',
                           'UN% (sc)', 'vFA (sc)', 'vFT (sc)', 'vFC (sc)', 'vFS (sc)', 'vFO (sc)',
                           'vSI (sc)', 'vSL (sc)', 'vCU (sc)', 'vKC (sc)', 'vEP (sc)', 'vCH (sc)',
                           'vSC (sc)', 'vKN (sc)', 'FA-X (sc)', 'FT-X (sc)', 'FC-X (sc)',
                           'FS-X (sc)', 'FO-X (sc)', 'SI-X (sc)', 'SL-X (sc)', 'CU-X (sc)',
                           'KC-X (sc)', 'EP-X (sc)', 'CH-X (sc)', 'SC-X (sc)', 'KN-X (sc)',
                           'FA-Z (sc)', 'FT-Z (sc)', 'FC-Z (sc)', 'FS-Z (sc)', 'FO-Z (sc)',
                           'SI-Z (sc)', 'SL-Z (sc)', 'CU-Z (sc)', 'KC-Z (sc)', 'EP-Z (sc)',
                           'CH-Z (sc)', 'SC-Z (sc)', 'KN-Z (sc)', 'wFA (sc)', 'wFT (sc)',
                           'wFC (sc)', 'wFS (sc)', 'wFO (sc)', 'wSI (sc)', 'wSL (sc)', 'wCU (sc)',
                           'wKC (sc)', 'wEP (sc)', 'wCH (sc)', 'wSC (sc)', 'wKN (sc)',
                           'wFA/C (sc)', 'wFT/C (sc)', 'wFC/C (sc)', 'wFS/C (sc)', 'wFO/C (sc)',
                           'wSI/C (sc)', 'wSL/C (sc)', 'wCU/C (sc)', 'wKC/C (sc)', 'wEP/C (sc)',
                           'wCH/C (sc)', 'wSC/C (sc)', 'wKN/C (sc)', 'O-Swing% (sc)',
                           'Z-Swing% (sc)', 'Swing% (sc)', 'O-Contact% (sc)', 'Z-Contact% (sc)',
                           'Contact% (sc)', 'Zone% (sc)', 'Pace', 'Def', 'wSB', 'UBR', 'Age Rng',
                           'Off', 'Lg', 'wGDP', 'Pull%', 'Cent%', 'Oppo%', 'Soft%', 'Med%',
                           'Hard%', 'TTO%', 'CH% (pi)', 'CS% (pi)', 'CU% (pi)', 'FA% (pi)',
                           'FC% (pi)', 'FS% (pi)', 'KN% (pi)', 'SB% (pi)', 'SI% (pi)', 'SL% (pi)',
                           'XX% (pi)', 'vCH (pi)', 'vCS (pi)', 'vCU (pi)', 'vFA (pi)', 'vFC (pi)',
                           'vFS (pi)', 'vKN (pi)', 'vSB (pi)', 'vSI (pi)', 'vSL (pi)', 'vXX (pi)',
                           'CH-X (pi)', 'CS-X (pi)', 'CU-X (pi)', 'FA-X (pi)', 'FC-X (pi)',
                           'FS-X (pi)', 'KN-X (pi)', 'SB-X (pi)', 'SI-X (pi)', 'SL-X (pi)',
                           'XX-X (pi)', 'CH-Z (pi)', 'CS-Z (pi)', 'CU-Z (pi)', 'FA-Z (pi)',
                           'FC-Z (pi)', 'FS-Z (pi)', 'KN-Z (pi)', 'SB-Z (pi)', 'SI-Z (pi)',
                           'SL-Z (pi)', 'XX-Z (pi)', 'wCH (pi)', 'wCS (pi)', 'wCU (pi)',
                           'wFA (pi)', 'wFC (pi)', 'wFS (pi)', 'wKN (pi)', 'wSB (pi)', 'wSI (pi)',
                           'wSL (pi)', 'wXX (pi)', 'wCH/C (pi)', 'wCS/C (pi)', 'wCU/C (pi)',
                           'wFA/C (pi)', 'wFC/C (pi)', 'wFS/C (pi)', 'wKN/C (pi)', 'wSB/C (pi)',
                           'wSI/C (pi)', 'wSL/C (pi)', 'wXX/C (pi)', 'O-Swing% (pi)',
                           'Z-Swing% (pi)', 'Swing% (pi)', 'O-Contact% (pi)', 'Z-Contact% (pi)',
                           'Contact% (pi)', 'Zone% (pi)', 'Pace (pi)', 'FRM', 'AVG+', 'BB%+',
                           'K%+', 'OBP+', 'SLG+', 'ISO+', 'BABIP+', 'LD+%', 'GB%+', 'FB%+',
                           'HR/FB%+', 'Pull%+', 'Cent%+', 'Oppo%+', 'Soft%+', 'Med%+', 'Hard%+',
                           'EV', 'LA', 'Barrels', 'Barrel%', 'maxEV', 'HardHit', 'HardHit%',
                           'Events', 'CStr%', 'CSW%']

# create new batting_adv table with specified columns i want
batting_adv = batting_filled[batting_adv_columns]

# renaming columns
batting_adv = batting_adv.rename(columns = {'name_common':'name',
                                            'G_y':'G',
                                            'PA_y':'PA',
                                            'WAR_x':'WAR'})

**Checking and cleaning `batting_basic` first:**

In [477]:
# check
batting_basic.head()

name  player_ID  year_ID team_ID lg_ID    salary   Age  \
0         Jeff Abbott  abbotje01     2000     CHW    AL  255000.0  27.0   
1         Kurt Abbott  abbotku01     2000     NYM    NL  500000.0  31.0   
2  Reggie Abercrombie  abercre01     2006     FLA    NL  327000.0  24.0   
3  Reggie Abercrombie  abercre01     2007     FLA    NL  327000.0  25.0   
4  Reggie Abercrombie  abercre01     2008     HOU    NL  327000.0  26.0   

       G     AB     PA    AVG     H    1B    2B   3B   HR     R   RBI    BB  \
0   80.0  215.0  242.0  0.274  59.0  40.0  15.0  1.0  3.0  31.0  29.0  21.0   
1   79.0  157.0  173.0  0.217  34.0  20.0   7.0  1.0  6.0  22.0  12.0  14.0   
2  111.0  255.0  281.0  0.212  54.0  35.0  12.0  2.0  5.0  39.0  24.0  18.0   
3   35.0   76.0   80.0  0.197  15.0  10.0   3.0  0.0  2.0  16.0   5.0   2.0   
4   34.0   55.0   60.0  0.309  17.0  10.0   5.0  0.0  2.0  10.0   5.0   1.0   

   IBB    SO  HBP   SF   SH  GDP   SB   CS    BB%     K%  BB/K    OBP    SLG  \
0  1.0  38.0  2.0  1.0  2.0  2.0  2.0  1.0  0.087  0.157  0.55  0.343  0.395   
1  2.0  51.0  1.0  1.0  0.0  2.0  1.0  1.0  0.081  0.295  0.27  0.283  0.389   
2  2.0  78.0  3.0  1.0  4.0  2.0  6.0  5.0  0.064  0.278  0.23  0.271  0.333   
3  0.0  22.0  2.0  0.0  0.0  1.0  7.0  1.0  0.025  0.275  0.09  0.238  0.316   
4  0.0  23.0  2.0  1.0  1.0  0.0  5.0  2.0  0.017  0.383  0.04  0.339  0.509   

     OPS    ISO  BABIP  
0  0.738  0.121  0.320  
1  0.672  0.172  0.277  
2  0.604  0.122  0.283  
3  0.553  0.118  0.250  
4  0.848  0.200  0.484

In [478]:
batting_basic.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12654 entries, 0 to 12653
Data columns (total 35 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   name       12654 non-null  object 
 1   player_ID  12654 non-null  object 
 2   year_ID    12654 non-null  int64  
 3   team_ID    12654 non-null  object 
 4   lg_ID      12654 non-null  object 
 5   salary     12654 non-null  float64
 6   Age        12340 non-null  float64
 7   G          12340 non-null  float64
 8   AB         12340 non-null  float64
 9   PA         12340 non-null  float64
 10  AVG        12340 non-null  float64
 11  H          12340 non-null  float64
 12  1B         12340 non-null  float64
 13  2B         12340 non-null  float64
 14  3B         12340 non-null  float64
 15  HR         12340 non-null  float64
 16  R          12340 non-null  float64
 17  RBI        12340 non-null  float64
 18  BB         12340 non-null  float64
 19  IBB        12340 non-null  float64
 20  SO    

In [479]:
# check missing values
batting_basic.isna().sum()

name           0
player_ID      0
year_ID        0
team_ID        0
lg_ID          0
salary         0
Age          314
G            314
AB           314
PA           314
AVG          314
H            314
1B           314
2B           314
3B           314
HR           314
R            314
RBI          314
BB           314
IBB          314
SO           314
HBP          314
SF           314
SH           314
GDP          314
SB           314
CS           314
BB%          314
K%           314
BB/K         314
OBP          314
SLG          314
OPS          314
ISO          314
BABIP        314
dtype: int64

**Handling missing values in `batting_basic`**

There are 314 missing values for standard batting statistics which is strange. When checking these missing values in `batting_basic`, there are fairly well-known players with missing statistics. This may be attributed to a scraping bug or data collection error on FanGraphs. 

While we could theoretically look up these players statistics, we'll just drop these missing rows from `batting_basic`. 

In [480]:
# drop all missing nan rows
batting_basic = batting_basic.dropna()

In [481]:
# check
batting_basic.isna().sum()

name         0
player_ID    0
year_ID      0
team_ID      0
lg_ID        0
salary       0
Age          0
G            0
AB           0
PA           0
AVG          0
H            0
1B           0
2B           0
3B           0
HR           0
R            0
RBI          0
BB           0
IBB          0
SO           0
HBP          0
SF           0
SH           0
GDP          0
SB           0
CS           0
BB%          0
K%           0
BB/K         0
OBP          0
SLG          0
OPS          0
ISO          0
BABIP        0
dtype: int64

In [482]:
batting_basic.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12340 entries, 0 to 12653
Data columns (total 35 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   name       12340 non-null  object 
 1   player_ID  12340 non-null  object 
 2   year_ID    12340 non-null  int64  
 3   team_ID    12340 non-null  object 
 4   lg_ID      12340 non-null  object 
 5   salary     12340 non-null  float64
 6   Age        12340 non-null  float64
 7   G          12340 non-null  float64
 8   AB         12340 non-null  float64
 9   PA         12340 non-null  float64
 10  AVG        12340 non-null  float64
 11  H          12340 non-null  float64
 12  1B         12340 non-null  float64
 13  2B         12340 non-null  float64
 14  3B         12340 non-null  float64
 15  HR         12340 non-null  float64
 16  R          12340 non-null  float64
 17  RBI        12340 non-null  float64
 18  BB         12340 non-null  float64
 19  IBB        12340 non-null  float64
 20  SO    

**Save `batting_basic` as a csv**

In [483]:
path = "Data/"

batting_basic.to_csv(path + 'batting_basic')

**Checking and cleaning `batting_adv`:**

In [484]:
batting_adv.head(3)

name  player_ID  year_ID team_ID lg_ID    salary   Age  \
0         Jeff Abbott  abbotje01     2000     CHW    AL  255000.0  27.0   
1         Kurt Abbott  abbotku01     2000     NYM    NL  500000.0  31.0   
2  Reggie Abercrombie  abercre01     2006     FLA    NL  327000.0  24.0   

       G     AB     PA    AVG     H    1B    2B   3B   HR     R   RBI    BB  \
0   80.0  215.0  242.0  0.274  59.0  40.0  15.0  1.0  3.0  31.0  29.0  21.0   
1   79.0  157.0  173.0  0.217  34.0  20.0   7.0  1.0  6.0  22.0  12.0  14.0   
2  111.0  255.0  281.0  0.212  54.0  35.0  12.0  2.0  5.0  39.0  24.0  18.0   

   IBB    SO  HBP   SF   SH  GDP   SB   CS    BB%     K%  BB/K    OBP    SLG  \
0  1.0  38.0  2.0  1.0  2.0  2.0  2.0  1.0  0.087  0.157  0.55  0.343  0.395   
1  2.0  51.0  1.0  1.0  0.0  2.0  1.0  1.0  0.081  0.295  0.27  0.283  0.389   
2  2.0  78.0  3.0  1.0  4.0  2.0  6.0  5.0  0.064  0.278  0.23  0.271  0.333   

     OPS    ISO  BABIP  runs_above_avg  runs_above_avg_off  \
0  0.738  0.121  0.320           -12.6                -6.7   
1  0.672  0.172  0.277            -9.1                -6.8   
2  0.604  0.122  0.283           -15.6               -11.6   

   runs_above_avg_def  WAR_rep   WAA   WAR    GB    FB    LD  IFFB  Pitches  \
0                -7.3     0.84 -1.13 -0.29   NaN   NaN   NaN   NaN      NaN   
1                 0.6     0.52 -0.93 -0.41   NaN   NaN   NaN   NaN      NaN   
2                -3.1     0.84 -1.58 -0.74  93.0  59.0  19.0   9.0    990.0   

   Balls  Strikes   IFH    BU  BUH    BB%     K%  BB/K    OBP    SLG    OPS  \
0    NaN      NaN   NaN   NaN  NaN  0.087  0.157  0.55  0.343  0.395  0.738   
1    NaN      NaN   NaN   NaN  NaN  0.081  0.295  0.27  0.283  0.389  0.672   
2  307.0    683.0  11.0  11.0  5.0  0.064  0.278  0.23  0.271  0.333  0.604   

     ISO  BABIP   GB/FB    LD%    GB%    FB%  IFFB%  HR/FB   IFH%   BUH%  \
0  0.121  0.320     NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
1  0.172  0.277     NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
2  0.122  0.283  0.0158  0.111  0.544  0.345  0.153  0.085  0.118  0.455   

    wOBA  wRAA   wRC   Bat  Fld  Rep  Pos   RAR  Spd  wRC+   WPA  -WPA  +WPA  \
0  0.328  -2.7  29.0  -4.2 -5.0  7.8 -1.6  -2.1  3.9  87.0  0.37 -3.89  4.26   
1  0.289  -7.8  15.0  -7.7 -2.0  5.6  1.5  -2.6  4.2  67.0 -0.40 -3.05  2.65   
2  0.264 -16.3  19.0 -16.9 -5.6  8.8  0.9 -10.3  6.2  54.0 -1.40 -5.31  3.90   

    RE24   REW   pLI  phLI    PH  WPA/LI  Clutch  FB% (Pitch)   FBv    SL%  \
0  -6.74 -0.57  0.90  1.79  14.0   -0.16    0.57          NaN   NaN    NaN   
1 -12.42 -1.20  0.95  1.12  16.0   -0.88    0.46          NaN   NaN    NaN   
2 -12.00 -1.18  0.96  0.98  10.0   -0.94   -0.52        0.524  89.8  0.254   

    SLv    CT%   CTv    CB%   CBv    CH%   CHv    SF%   SFv  KN%  KNv    XX%  \
0   NaN    NaN   NaN    NaN   NaN    NaN   NaN    NaN   NaN  NaN  NaN    NaN   
1   NaN    NaN   NaN    NaN   NaN    NaN   NaN    NaN   NaN  NaN  NaN    NaN   
2  82.3  0.024  86.5  0.091  74.3  0.102  79.2  0.005  87.8  NaN  NaN  0.029   

   PO%   wFB  wSL  wCT  wCB  wCH  wSF  wKN  wFB/C  wSL/C  wCT/C  wCB/C  wCH/C  \
0  NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN    NaN    NaN    NaN    NaN    NaN   
1  NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN    NaN    NaN    NaN    NaN    NaN   
2  NaN -10.0  1.4 -1.9 -4.3  2.3 -0.3  NaN  -1.98   0.56   -8.1   -4.9   2.36   

   wSF/C  wKN/C  O-Swing%  Z-Swing%  Swing%  O-Contact%  Z-Contact%  Contact%  \
0    NaN    NaN       NaN       NaN     NaN         NaN         NaN       NaN   
1    NaN    NaN       NaN       NaN     NaN         NaN         NaN       NaN   
2   -6.0    NaN     0.383     0.794   0.589       0.452       0.779     0.673   

   Zone%  F-Strike%  SwStr%  BsR  FA% (sc)  FT% (sc)  FC% (sc)  FS% (sc)  \
0    NaN        NaN     NaN  0.0       NaN       NaN       NaN       NaN   
1    NaN        NaN     NaN -0.2       NaN       NaN       NaN       NaN   
2    0.5      0.719   0.191  1.8       NaN       NaN     

In [485]:
# check missing values
batting_adv.isna().sum()

name            0
player_ID       0
year_ID         0
team_ID         0
lg_ID           0
             ... 
HardHit      4268
HardHit%     8877
Events        314
CStr%        1477
CSW%         1477
Length: 330, dtype: int64

**Handling missing values in `batting_adv`**

Unfortunately, we have many missing values in the `batting_adv` table. This is expected, since there is a lot of variance when it comes to collecting advanced StatCast data. 

Lets limit `batting_adv` to data between 2014 and 2021 and fill in the remaining missing values with 0s. 

In [486]:
batting_adv = batting_adv[batting_adv['year_ID'] >= 2014]

In [487]:
# remove rows where stats were not scraped properly (same as in batting_basic table)
# rows where 
batting_adv = batting_adv[batting_adv['Age'].notna()]

In [488]:
# fill all missing NaNs with 0
batting_adv = batting_adv.fillna(0)

REMOVE AGE RNG COLUMN

In [513]:
batting_adv[batting_adv['name'] == 'Aaron Judge']

name  player_ID  year_ID team_ID lg_ID      salary   Age      G  \
6043  Aaron Judge  judgeaa01     2016     NYY    AL    544500.0  24.0   27.0   
6044  Aaron Judge  judgeaa01     2017     NYY    AL    544500.0  25.0  155.0   
6045  Aaron Judge  judgeaa01     2018     NYY    AL    622300.0  26.0  112.0   
6046  Aaron Judge  judgeaa01     2019     NYY    AL    684300.0  27.0  102.0   
6047  Aaron Judge  judgeaa01     2020     NYY    AL   8500000.0  28.0   28.0   
6048  Aaron Judge  judgeaa01     2021     NYY    AL  10175000.0  29.0  148.0   

         AB     PA    AVG      H    1B    2B   3B    HR      R    RBI     BB  \
6043   84.0   95.0  0.179   15.0   9.0   2.0  0.0   4.0   10.0   10.0    9.0   
6044  542.0  678.0  0.284  154.0  75.0  24.0  3.0  52.0  128.0  114.0  127.0   
6045  413.0  498.0  0.278  115.0  66.0  22.0  0.0  27.0   77.0   67.0   76.0   
6046  378.0  447.0  0.272  103.0  57.0  18.0  1.0  27.0   75.0   55.0   64.0   
6047  101.0  114.0  0.257   26.0  14.0   3.0  0.0   9.0   23.0   22.0   10.0   
6048  550.0  633.0  0.287  158.0  95.0  24.0  0.0  39.0   89.0   98.0   75.0   

       IBB     SO  HBP   SF   SH   GDP   SB   CS    BB%     K%  BB/K    OBP  \
6043   0.0   42.0  1.0  1.0  0.0   2.0  0.0  1.0  0.095  0.442  0.21  0.263   
6044  11.0  208.0  5.0  4.0  0.0  15.0  9.0  4.0  0.187  0.307  0.61  0.422   
6045   3.0  152.0  4.0  5.0  0.0  10.0  6.0  3.0  0.153  0.305  0.50  0.392   
6046   4.0  141.0  3.0  1.0  0.0  11.0  3.0  2.0  0.143  0.315  0.45  0.381   
6047   0.0   32.0  2.0  0.0  0.0   5.0  0.0  1.0  0.088  0.281  0.31  0.336   
6048   2.0  158.0  3.0  5.0  0.0  16.0  6.0  1.0  0.118  0.250  0.47  0.373   

        SLG    OPS    ISO  BABIP  runs_above_avg  runs_above_avg_off  \
6043  0.345  0.608  0.167  0.282            -6.1                -6.1   
6044  0.627  1.049  0.343  0.357            57.2                49.2   
6045  0.528  0.919  0.249  0.368            39.5                23.5   
6046  0.540  0.921  0.267  0.360            40.8                19.8   
6047  0.554  0.891  0.297  0.283             7.7                 4.7   
6048  0.544  0.916  0.256  0.332            38.4                28.4   

      runs_above_avg_def  WAR_rep   WAA   WAR     GB     FB    LD  IFFB  \
6043                -0.9     0.33 -0.62 -0.29   15.0   22.0   6.0   0.0   
6044                 1.6     2.27  5.72  7.99  118.0  146.0  74.0   9.0   
6045                10.9     1.62  4.25  5.87  111.0   93.0  62.0   5.0   
6046                16.5     1.48  4.13  5.61   96.0   77.0  65.0   2.0   
6047                 2.0     0.38  0.75  1.13   27.0   28.0  14.0   0.0   
6048                 4.1     2.08  3.96  6.04  164.0  141.0  92.0   5.0   

      Pitches   Balls  Strikes   IFH   BU  BUH    BB%     K%  BB/K    OBP  \
6043    408.0   149.0    259.0   1.0  0.0  0.0  0.095  0.442  0.21  0.263   
6044   2989.0  1292.0   1697.0   5.0  0.0  0.0  0.187  0.307  0.61  0.422   
6045   2124.0   889.0   1235.0  10.0  0.0  0.0  0.153  0.305  0.50  0.392   
6046   1914.0   785.0   1129.0   6.0  0.0  0.0  0.143  0.315  0.45  0.381   
6047    487.0   197.0    290.0   2.0  0.0  0.0  0.088  0.281  0.31  0.336   
6048   2654.0  1075.0   1579.0  10.0  0.0  0.0  0.118  0.250  0.47  0.373   

        SLG    OPS    ISO  BABIP   GB/FB    LD%    GB%    FB%  IFFB%  HR/FB  \
6043  0.345  0.608  0.167  0.282  0.0068  0.140  0.349  0.512  0.000  0.182   
6044  0.627  1.049  0.343  0.357  0.0081  0.219  0.349  0.432  0.062  0.356   
6045  0.528  0.919  0.249  0.368  0.0119  0.233  0.417  0.350  0.054  0.290   
6046  0.540  0.921  0.267  0.360  0.0125  0.273  0.403  0.324  0.026  0.351   
6047  0.554  0.891  0.297  0.283  0.0096  0.203  0.391  0.406  0.000  0.321   
6048  0.544  0.916  0.256  0.332  0.0116  0.232  0.413  0.355  0.035  0.277   

       IFH%  BUH%   wOBA  wRAA    wRC   Bat   Fld   Rep  Pos   RAR  Spd  \
6043  0.067   0.0  0.267  -4.0    7.0  -4.3   1.2   2.9 -1.1  -1.5  2.1   
6044  0.042   0.0  0.430  62.5  145.0  61.7  11.6  21.0 -7.5  

**Save `batting_adv` as a csv**

In [490]:
path = "Data/"

batting_adv.to_csv(path + 'batting_adv')

## Formatting the Pitching Table

**Join `pitching_2021` with `bwar_pitch_2021` on the following columns:**

**`pitching_2021`** 
- `Name`
- `Season`

**`bwar_pitch_2021`**  
- `name_common`
- `year_ID`

In [491]:
# join pitching_2021 onto bwar_pitch_2021 (left join)
pitching_merged = pd.merge(bwar_pitch_2021, pitching_2021, how='left',left_on=['name_common','year_ID'],right_on=['Name','Season'])

In [492]:
# check
pitching_merged

name_common   age    mlb_ID  player_ID  year_ID team_ID  stint_ID  \
0      David Aardsma  22.0  430911.0  aardsda01     2004     SFG         1   
1      David Aardsma  24.0  430911.0  aardsda01     2006     CHC         1   
2      David Aardsma  25.0  430911.0  aardsda01     2007     CHW         1   
3      David Aardsma  26.0  430911.0  aardsda01     2008     BOS         1   
4      David Aardsma  27.0  430911.0  aardsda01     2009     SEA         1   
...              ...   ...       ...        ...      ...     ...       ...   
16570    Joel Zumaya  24.0  451491.0  zumayjo01     2009     DET         1   
16571    Joel Zumaya  25.0  451491.0  zumayjo01     2010     DET         1   
16572      Tony Zych  24.0  543964.0   zychto01     2015     SEA         1   
16573      Tony Zych  25.0  543964.0   zychto01     2016     SEA         1   
16574      Tony Zych  26.0  543964.0   zychto01     2017     SEA         1   

      lg_ID  G_x  GS_x  IPouts  IPouts_start  IPouts_relief  RA     xRA  \
0        NL   11     0      32           0.0           32.0   8   5.967   
1        NL   45     0     159           0.0          159.0  25  28.172   
2        AL   25     0      97           0.0           97.0  24  17.999   
3        AL   47     0     146           0.0          146.0  32  26.131   
4        AL   73     0     214           0.0          214.0  23  39.221   
...     ...  ...   ...     ...           ...            ...  ..     ...   
16570    AL   29     0      93           0.0           93.0  18  17.186   
16571    AL   31     0     115           0.0          115.0  13  19.185   
16572    AL   13     1      55           8.0           47.0   6   9.126   
16573    AL   12     0      41           0.0           41.0   6   6.751   
16574    AL   45     0     122           0.0          122.0  12  21.448   

       xRA_sprp_adj  xRA_extras_adj  xRA_def_pitcher  PPF  PPF_custom  \
0            -0.440             NaN           -0.423  101      98.525   
1            -2.076             NaN           -0.367  103     104.018   
2            -1.343             NaN           -1.327  104     103.205   
3            -1.942             NaN            0.663  106     106.614   
4            -2.895             NaN            3.136   95      93.595   
...             ...             ...              ...  ...         ...   
16570        -1.268             NaN            0.767  101     100.523   
16571        -1.471             NaN            0.559  101      99.692   
16572        -0.525             NaN           -0.706   95      92.553   
16573        -0.487             NaN            0.059   96      98.600   
16574        -1.497             NaN            0.542   95      95.353   

       xRA_final    BIP  BIP_perc  RS_def_total  runs_above_avg  \
0          5.862   44.0    0.0093         -45.5          -2.138   
1         27.526  147.0    0.0337         -10.9           2.526   
2         18.559   97.0    0.0206         -64.4          -5.441   
3         25.082  139.0    0.0317          20.9          -6.918   
4         31.064  181.0    0.0399          78.6           8.064   
...          ...    ...       ...           ...             ...   
16570     15.230   96.0    0.0213          36.0          -2.770   
16571     17.102  111.0    0.0245          22.8           4.102   
16572      8.614   47.0    0.0107         -66.0           2.614   
16573      6.118   28.0    0.0065           9.0           0.118   
16574     18.507  112.0    0.0258          21.0           6.507   

       runs_above_avg_adj  runs_above_rep  RpO_replacement  \
0                  -2.177          -1.199            0.203   
1                   2.751           7.388            0.211   
2                  -5.646          -1.814            0.218   
3                  -7.757          -1.633            0.211   
4                   7.689          15.965            0.215   
...                   ...             ...              ...   
16570              -2.933           0.664            0.

**Filling missing `salary` values.**

Similar to filling in missing `salary` values for the batting table, we will apply the same function to the `pitching_merged` table. 

To fill in these missing values, we will assume the following:
- A player's salary is the same across consecutive seasons even if the salary is missing
- Players traded mid-season will have the same salary for that season across both teams


In [493]:
# make a copy and specify which column to fill missing values
salary_col = ['salary']
pitching_filled = pitching_merged.copy()

In [494]:
# forward and backward fills missing values grouped by name
pitching_filled.loc[:,salary_col] = pitching_merged.loc[:,salary_col].groupby(pitching_filled['name_common']).ffill().bfill()

In [495]:
# check
pitching_filled['salary'].isna().sum()

0

In [496]:
# check
pitching_merged[['name_common', 'year_ID', 'salary']].head(15)

name_common  year_ID     salary
0   David Aardsma     2004   300000.0
1   David Aardsma     2006        NaN
2   David Aardsma     2007   387500.0
3   David Aardsma     2008   403250.0
4   David Aardsma     2009   419000.0
5   David Aardsma     2010  2750000.0
6   David Aardsma     2012   500000.0
7   David Aardsma     2013        NaN
8   David Aardsma     2015        NaN
9   Fernando Abad     2010        NaN
10  Fernando Abad     2011   418000.0
11  Fernando Abad     2012   485000.0
12  Fernando Abad     2013        NaN
13  Fernando Abad     2014   525900.0
14  Fernando Abad     2015  1087500.0

In [497]:
# check
pitching_filled[['name_common', 'year_ID', 'salary']].head(15)

name_common  year_ID     salary
0   David Aardsma     2004   300000.0
1   David Aardsma     2006   300000.0
2   David Aardsma     2007   387500.0
3   David Aardsma     2008   403250.0
4   David Aardsma     2009   419000.0
5   David Aardsma     2010  2750000.0
6   David Aardsma     2012   500000.0
7   David Aardsma     2013   500000.0
8   David Aardsma     2015   500000.0
9   Fernando Abad     2010   418000.0
10  Fernando Abad     2011   418000.0
11  Fernando Abad     2012   485000.0
12  Fernando Abad     2013   485000.0
13  Fernando Abad     2014   525900.0
14  Fernando Abad     2015  1087500.0

In [498]:
pitching_filled

name_common   age    mlb_ID  player_ID  year_ID team_ID  stint_ID  \
0      David Aardsma  22.0  430911.0  aardsda01     2004     SFG         1   
1      David Aardsma  24.0  430911.0  aardsda01     2006     CHC         1   
2      David Aardsma  25.0  430911.0  aardsda01     2007     CHW         1   
3      David Aardsma  26.0  430911.0  aardsda01     2008     BOS         1   
4      David Aardsma  27.0  430911.0  aardsda01     2009     SEA         1   
...              ...   ...       ...        ...      ...     ...       ...   
16570    Joel Zumaya  24.0  451491.0  zumayjo01     2009     DET         1   
16571    Joel Zumaya  25.0  451491.0  zumayjo01     2010     DET         1   
16572      Tony Zych  24.0  543964.0   zychto01     2015     SEA         1   
16573      Tony Zych  25.0  543964.0   zychto01     2016     SEA         1   
16574      Tony Zych  26.0  543964.0   zychto01     2017     SEA         1   

      lg_ID  G_x  GS_x  IPouts  IPouts_start  IPouts_relief  RA     xRA  \
0        NL   11     0      32           0.0           32.0   8   5.967   
1        NL   45     0     159           0.0          159.0  25  28.172   
2        AL   25     0      97           0.0           97.0  24  17.999   
3        AL   47     0     146           0.0          146.0  32  26.131   
4        AL   73     0     214           0.0          214.0  23  39.221   
...     ...  ...   ...     ...           ...            ...  ..     ...   
16570    AL   29     0      93           0.0           93.0  18  17.186   
16571    AL   31     0     115           0.0          115.0  13  19.185   
16572    AL   13     1      55           8.0           47.0   6   9.126   
16573    AL   12     0      41           0.0           41.0   6   6.751   
16574    AL   45     0     122           0.0          122.0  12  21.448   

       xRA_sprp_adj  xRA_extras_adj  xRA_def_pitcher  PPF  PPF_custom  \
0            -0.440             NaN           -0.423  101      98.525   
1            -2.076             NaN           -0.367  103     104.018   
2            -1.343             NaN           -1.327  104     103.205   
3            -1.942             NaN            0.663  106     106.614   
4            -2.895             NaN            3.136   95      93.595   
...             ...             ...              ...  ...         ...   
16570        -1.268             NaN            0.767  101     100.523   
16571        -1.471             NaN            0.559  101      99.692   
16572        -0.525             NaN           -0.706   95      92.553   
16573        -0.487             NaN            0.059   96      98.600   
16574        -1.497             NaN            0.542   95      95.353   

       xRA_final    BIP  BIP_perc  RS_def_total  runs_above_avg  \
0          5.862   44.0    0.0093         -45.5          -2.138   
1         27.526  147.0    0.0337         -10.9           2.526   
2         18.559   97.0    0.0206         -64.4          -5.441   
3         25.082  139.0    0.0317          20.9          -6.918   
4         31.064  181.0    0.0399          78.6           8.064   
...          ...    ...       ...           ...             ...   
16570     15.230   96.0    0.0213          36.0          -2.770   
16571     17.102  111.0    0.0245          22.8           4.102   
16572      8.614   47.0    0.0107         -66.0           2.614   
16573      6.118   28.0    0.0065           9.0           0.118   
16574     18.507  112.0    0.0258          21.0           6.507   

       runs_above_avg_adj  runs_above_rep  RpO_replacement  \
0                  -2.177          -1.199            0.203   
1                   2.751           7.388            0.211   
2                  -5.646          -1.814            0.218   
3                  -7.757          -1.633            0.211   
4                   7.689          15.965            0.215   
...                   ...             ...              ...   
16570              -2.933           0.664            0.

## Simplify and separate the `pitching_filled` table

Similar to what we did above to the `batting_filled` table, we will now simplify into two separate tables for `pitching_filled`. 

Thus, we will create two separate pitching tables:
- `pitching_basic` (containing basic data between 2000 - 2021)
- `pitching_adv` (containing basic AND StatCast data between 2014 - 2021)

We'll also remove repetitive columns that we brought in during the initial merge of tables. 

In [499]:
pitching_filled.head(3)

name_common   age    mlb_ID  player_ID  year_ID team_ID  stint_ID lg_ID  \
0  David Aardsma  22.0  430911.0  aardsda01     2004     SFG         1    NL   
1  David Aardsma  24.0  430911.0  aardsda01     2006     CHC         1    NL   
2  David Aardsma  25.0  430911.0  aardsda01     2007     CHW         1    AL   

   G_x  GS_x  IPouts  IPouts_start  IPouts_relief  RA     xRA  xRA_sprp_adj  \
0   11     0      32           0.0           32.0   8   5.967        -0.440   
1   45     0     159           0.0          159.0  25  28.172        -2.076   
2   25     0      97           0.0           97.0  24  17.999        -1.343   

   xRA_extras_adj  xRA_def_pitcher  PPF  PPF_custom  xRA_final    BIP  \
0             NaN           -0.423  101      98.525      5.862   44.0   
1             NaN           -0.367  103     104.018     27.526  147.0   
2             NaN           -1.327  104     103.205     18.559   97.0   

   BIP_perc  RS_def_total  runs_above_avg  runs_above_avg_adj  runs_above_rep  \
0    0.0093         -45.5          -2.138              -2.177          -1.199   
1    0.0337         -10.9           2.526               2.751           7.388   
2    0.0206         -64.4          -5.441              -5.646          -1.814   

   RpO_replacement  GR_leverage_index_avg  WAR_x    salary  teamRpG   oppRpG  \
0            0.203                 1.0718  -0.15  300000.0  4.67092  4.86883   
1            0.211                 0.7542   0.61  300000.0  4.86675  4.80561   
2            0.218                 1.4280  -0.40  387500.0  4.85895  5.08479   

   pyth_exponent  waa_win_perc     WAA  WAA_adj  oppRpG_rep  \
0          1.902        0.4803 -0.2167  -0.0298     4.75633   
1          1.909        0.5060  0.2700  -0.1301     4.97303   
2          1.924        0.4782 -0.5450  -0.1990     5.00394   

   pyth_exponent_rep  waa_win_perc_rep  WAR_rep    ERA_plus   ER_lg    IDfg  \
0              1.895            0.4914   0.0942   66.675000   5.334     NaN   
1              1.919            0.4896   0.4682  114.295833  27.431  1902.0   
2              1.920            0.4859   0.3459   74.086957  17.040  1902.0   

   Season           Name Team   Age    W    L  WAR_y   ERA   G_y  GS_y   CG  \
0     NaN            NaN  NaN   NaN  NaN  NaN    NaN   NaN   NaN   NaN  NaN   
1  2006.0  David Aardsma  CHC  24.0  3.0  0.0   -0.2  4.08  45.0   0.0  0.0   
2  2007.0  David Aardsma  CHW  25.0  2.0  1.0    0.2  6.40  25.0   0.0  0.0   

   ShO   SV   BS    IP    TBF     H     R    ER   HR    BB  IBB  HBP   WP  \
0  NaN  NaN  NaN   NaN    NaN   NaN   NaN   NaN  NaN   NaN  NaN  NaN  NaN   
1  0.0  0.0  0.0  53.0  225.0  41.0  25.0  24.0  9.0  28.0  0.0  1.0  1.0   
2  0.0  0.0  3.0  32.1  151.0  39.0  24.0  23.0  4.0  17.0  3.0  1.0  2.0   

    BK    SO    GB    FB    LD  IFFB  Balls  Strikes  Pitches    RS  IFH   BU  \
0  NaN   NaN   NaN   NaN   NaN   NaN    NaN      NaN      NaN   NaN  NaN  NaN   
1  0.0  49.0  54.0  64.0  28.0   5.0  361.0    601.0    962.0  33.0  3.0  1.0   
2  0.0  36.0  35.0  40.0  20.0   2.0  244.0    364.0    608.0  10.0  3.0  2.0   

   BUH    K/9  BB/9  K/BB    H/9  HR/9    AVG  WHIP  BABIP   LOB%   FIP  \
0  NaN    NaN   NaN   NaN    NaN   NaN    NaN   NaN    NaN    NaN   NaN   
1  0.0   8.32  4.75  1.75   6.96  1.53  0.209  1.30  0.232  0.784  5.15   
2  0.0  10.02  4.73  2.12  10.86  1.11  0.293  1.73  0.376  0.642  4.29   

   GB/FB    LD%    GB%    FB%  IFFB%  HR/FB   IFH%  BUH%  Starting  Start-IP  \
0    NaN    NaN    NaN    NaN    NaN    NaN    NaN   NaN       NaN       NaN   
1   0.84  0.192  0.370  0.438  0.078  0.141  0.056   0.0       NaN       NaN   
2   0.88  0.211  0.368  0.421  0.050  0.100  0.086   0.0       NaN       NaN   

   Relieving  Relief-IP  RAR Dollars  tERA  xFIP   WPA  -WPA  +WPA  RE24  \
0        NaN        NaN  NaN     NaN   NaN   NaN   NaN   NaN   NaN   NaN   
1       -1.6       53.0 -1.6  ($0.7)  5.49  4.64  1.04 -1.86  2.90  8.11   
2        2.2       32.1  2.2    $1.2  4.58  4.23 -0.26 -3

In [500]:
# get all column names
with pd.option_context('display.max_seq_items', None):
    print (pitching_filled.columns)

Index(['name_common', 'age', 'mlb_ID', 'player_ID', 'year_ID', 'team_ID',
       'stint_ID', 'lg_ID', 'G_x', 'GS_x', 'IPouts', 'IPouts_start',
       'IPouts_relief', 'RA', 'xRA', 'xRA_sprp_adj', 'xRA_extras_adj',
       'xRA_def_pitcher', 'PPF', 'PPF_custom', 'xRA_final', 'BIP', 'BIP_perc',
       'RS_def_total', 'runs_above_avg', 'runs_above_avg_adj',
       'runs_above_rep', 'RpO_replacement', 'GR_leverage_index_avg', 'WAR_x',
       'salary', 'teamRpG', 'oppRpG', 'pyth_exponent', 'waa_win_perc', 'WAA',
       'WAA_adj', 'oppRpG_rep', 'pyth_exponent_rep', 'waa_win_perc_rep',
       'WAR_rep', 'ERA_plus', 'ER_lg', 'IDfg', 'Season', 'Name', 'Team', 'Age',
       'W', 'L', 'WAR_y', 'ERA', 'G_y', 'GS_y', 'CG', 'ShO', 'SV', 'BS', 'IP',
       'TBF', 'H', 'R', 'ER', 'HR', 'BB', 'IBB', 'HBP', 'WP', 'BK', 'SO', 'GB',
       'FB', 'LD', 'IFFB', 'Balls', 'Strikes', 'Pitches', 'RS', 'IFH', 'BU',
       'BUH', 'K/9', 'BB/9', 'K/BB', 'H/9', 'HR/9', 'AVG', 'WHIP', 'BABIP',
       'LOB%', 'FIP', '

**Specify columns for `pitching_basic`**

In [501]:
# basic pitching columns to keep
pitching_basic_columns = ['name_common', 'player_ID', 'year_ID', 'team_ID', 'lg_ID',
                         'salary', 'Age', 'W', 'L', 'WAR_y', 'ERA', 'G_y', 'GS_y', 
                          'CG', 'ShO', 'SV', 'BS', 'IP', 'TBF', 'H', 'RA', 'ER', 'HR', 
                          'BB', 'IBB', 'HBP', 'WP', 'BK', 'SO', 'GB','FB', 'LD', 'IFFB',
                          'Balls', 'Strikes', 'Pitches', 'RS', 'IFH', 'BU','BUH', 'K/9', 
                          'BB/9', 'K/BB', 'H/9', 'HR/9', 'AVG', 'WHIP', 'BABIP','LOB%', 
                          'FIP', 'GB/FB', 'LD%', 'GB%', 'FB%', 'IFFB%', 'HR/FB', 'IFH%',
                          'BUH%']

# create new pitching_basic table with specified columns i want
pitching_basic = pitching_filled[pitching_basic_columns]

# renaming columns
pitching_basic = pitching_basic.rename(columns = {'name_common':'name',
                                                  'WAR_y': 'WAR',
                                                  'G_y':'G',
                                                  'GS_y':'GS'})

**Specify columns for `pitching_adv`**

In [502]:
# adv pitching columns to keep
pitching_adv_columns = ['name_common', 'player_ID', 'year_ID', 'team_ID', 'lg_ID',
                           'salary', 'Age', 'W', 'L', 'WAR_y', 'ERA', 'G_y', 'GS_y', 
                           'CG', 'ShO', 'SV', 'BS', 'IP', 'TBF', 'H', 'RA', 'ER', 'HR', 
                           'BB', 'IBB', 'HBP', 'WP', 'BK', 'SO', 'GB','FB', 'LD', 'IFFB',
                           'Balls', 'Strikes', 'Pitches', 'RS', 'IFH', 'BU','BUH', 'K/9', 
                           'BB/9', 'K/BB', 'H/9', 'HR/9', 'AVG', 'WHIP', 'BABIP','LOB%', 
                           'FIP', 'GB/FB', 'LD%', 'GB%', 'FB%', 'IFFB%', 'HR/FB', 'IFH%',
                           'BUH%', 'xRA', 'xRA_sprp_adj', 'xRA_extras_adj','xRA_def_pitcher', 
                           'PPF', 'PPF_custom', 'xRA_final', 'BIP', 'BIP_perc', 'RS_def_total', 
                           'runs_above_avg', 'runs_above_avg_adj', 'runs_above_rep', 'RpO_replacement', 
                           'GR_leverage_index_avg','ERA_plus','tERA', 'xFIP', 'WPA', '-WPA', '+WPA', 
                           'RE24', 'REW', 'pLI', 'inLI', 'gmLI', 'exLI', 'Pulls', 'WPA/LI', 'Clutch', 'FB% 2', 'FBv',
                           'SL%', 'SLv', 'CT%', 'CTv', 'CB%', 'CBv', 'CH%', 'CHv', 'SF%', 'SFv',
                           'KN%', 'KNv', 'XX%', 'PO%', 'wFB', 'wSL', 'wCT', 'wCB', 'wCH', 'wSF',
                           'wKN', 'wFB/C', 'wSL/C', 'wCT/C', 'wCB/C', 'wCH/C', 'wSF/C', 'wKN/C',
                           'O-Swing%', 'Z-Swing%', 'Swing%', 'O-Contact%', 'Z-Contact%',
                           'Contact%', 'Zone%', 'F-Strike%', 'SwStr%', 'HLD', 'SD', 'MD', 'ERA-',
                           'FIP-', 'xFIP-', 'K%', 'BB%', 'SIERA', 'RS/9', 'E-F', 'FA% (sc)',
                           'FT% (sc)', 'FC% (sc)', 'FS% (sc)', 'FO% (sc)', 'SI% (sc)', 'SL% (sc)',
                           'CU% (sc)', 'KC% (sc)', 'EP% (sc)', 'CH% (sc)', 'SC% (sc)', 'KN% (sc)',
                           'UN% (sc)', 'vFA (sc)', 'vFT (sc)', 'vFC (sc)', 'vFS (sc)', 'vFO (sc)',
                           'vSI (sc)', 'vSL (sc)', 'vCU (sc)', 'vKC (sc)', 'vEP (sc)', 'vCH (sc)',
                           'vSC (sc)', 'vKN (sc)', 'FA-X (sc)', 'FT-X (sc)', 'FC-X (sc)',
                           'FS-X (sc)', 'FO-X (sc)', 'SI-X (sc)', 'SL-X (sc)', 'CU-X (sc)',
                           'KC-X (sc)', 'EP-X (sc)', 'CH-X (sc)', 'SC-X (sc)', 'KN-X (sc)',
                           'FA-Z (sc)', 'FT-Z (sc)', 'FC-Z (sc)', 'FS-Z (sc)', 'FO-Z (sc)',
                           'SI-Z (sc)', 'SL-Z (sc)', 'CU-Z (sc)', 'KC-Z (sc)', 'EP-Z (sc)',
                           'CH-Z (sc)', 'SC-Z (sc)', 'KN-Z (sc)', 'wFA (sc)', 'wFT (sc)',
                           'wFC (sc)', 'wFS (sc)', 'wFO (sc)', 'wSI (sc)', 'wSL (sc)', 'wCU (sc)',
                           'wKC (sc)', 'wEP (sc)', 'wCH (sc)', 'wSC (sc)', 'wKN (sc)',
                           'wFA/C (sc)', 'wFT/C (sc)', 'wFC/C (sc)', 'wFS/C (sc)', 'wFO/C (sc)',
                           'wSI/C (sc)', 'wSL/C (sc)', 'wCU/C (sc)', 'wKC/C (sc)', 'wEP/C (sc)',
                           'wCH/C (sc)', 'wSC/C (sc)', 'wKN/C (sc)', 'O-Swing% (sc)',
                           'Z-Swing% (sc)', 'Swing% (sc)', 'O-Contact% (sc)', 'Z-Contact% (sc)',
                           'Contact% (sc)', 'Zone% (sc)', 'Pace', 'RA9-WAR', 'BIP-Wins',
                           'LOB-Wins', 'FDP-Wins', 'Age Rng', 'K-BB%', 'Pull%', 'Cent%', 'Oppo%',
                           'Soft%', 'Med%', 'Hard%', 'kwERA', 'TTO%', 'CH% (pi)', 'CS% (pi)',
                           'CU% (pi)', 'FA% (pi)', 'FC% (pi)', 'FS% (pi)', 'KN% (pi)', 'SB% (pi)',
                           'SI% (pi)', 'SL% (pi)', 'XX% (pi)', 'vCH (pi)', 'vCS (pi)', 'vCU (pi)',
                           'vFA (pi)', 'vFC (pi)', 'vFS (pi)', 'vKN (pi)', 'vSB (pi)', 'vSI (pi)',
                           'vSL (pi)', 'vXX (pi)', 'CH-X (pi)', 'CS-X (pi)', 'CU-X (pi)',
                           'FA-X (pi)', 'FC-X (pi)', 'FS-X (pi)', 'KN-X (pi)', 'SB-X (pi)',
                           'SI-X (pi)', 'SL-X (pi)', 'XX-X (pi)', 'CH-Z (pi)', 'CS-Z (pi)',
                           'CU-Z (pi)', 'FA-Z (pi)', 'FC-Z (pi)', 'FS-Z (pi)', 'KN-Z (pi)',
                           'SB-Z (pi)', 'SI-Z (pi)', 'SL-Z (pi)', 'XX-Z (pi)', 'wCH (pi)',
                           'wCS (pi)', 'wCU (pi)', 'wFA (pi)', 'wFC (pi)', 'wFS (pi)', 'wKN (pi)',
                           'wSB (pi)', 'wSI (pi)', 'wSL (pi)', 'wXX (pi)', 'wCH/C (pi)',
                           'wCS/C (pi)', 'wCU/C (pi)', 'wFA/C (pi)', 'wFC/C (pi)', 'wFS/C (pi)',
                           'wKN/C (pi)', 'wSB/C (pi)', 'wSI/C (pi)', 'wSL/C (pi)', 'wXX/C (pi)',
                           'O-Swing% (pi)', 'Z-Swing% (pi)', 'Swing% (pi)', 'O-Contact% (pi)',
                           'Z-Contact% (pi)', 'Contact% (pi)', 'Zone% (pi)', 'Pace (pi)', 'FRM',
                           'K/9+', 'BB/9+', 'K/BB+', 'H/9+', 'HR/9+', 'AVG+', 'WHIP+', 'BABIP+',
                           'LOB%+', 'K%+', 'BB%+', 'LD%+', 'GB%+', 'FB%+', 'HR/FB%+', 'Pull%+',
                           'Cent%+', 'Oppo%+', 'Soft%+', 'Med%+', 'Hard%+', 'EV', 'LA', 'Barrels',
                           'Barrel%', 'maxEV', 'HardHit', 'HardHit%', 'Events', 'CStr%', 'CSW%',
                           'xERA']

# create new batting_adv table with specified columns i want
pitching_adv = pitching_filled[pitching_adv_columns]

# renaming columns
pitching_adv = pitching_adv.rename(columns = {'name_common':'name',
                                              'WAR_y': 'WAR',
                                              'G_y':'G',
                                              'GS_y':'GS'})

**Checking and cleaning `pitching_basic` first:**

In [503]:
# check
pitching_basic.head()

name  player_ID  year_ID team_ID lg_ID    salary   Age    W    L  \
0  David Aardsma  aardsda01     2004     SFG    NL  300000.0   NaN  NaN  NaN   
1  David Aardsma  aardsda01     2006     CHC    NL  300000.0  24.0  3.0  0.0   
2  David Aardsma  aardsda01     2007     CHW    AL  387500.0  25.0  2.0  1.0   
3  David Aardsma  aardsda01     2008     BOS    AL  403250.0  26.0  4.0  2.0   
4  David Aardsma  aardsda01     2009     SEA    AL  419000.0  27.0  3.0  6.0   

   WAR   ERA     G   GS   CG  ShO    SV   BS    IP    TBF     H  RA    ER  \
0  NaN   NaN   NaN  NaN  NaN  NaN   NaN  NaN   NaN    NaN   NaN   8   NaN   
1 -0.2  4.08  45.0  0.0  0.0  0.0   0.0  0.0  53.0  225.0  41.0  25  24.0   
2  0.2  6.40  25.0  0.0  0.0  0.0   0.0  3.0  32.1  151.0  39.0  24  23.0   
3 -0.1  5.55  47.0  0.0  0.0  0.0   0.0  1.0  48.2  228.0  49.0  32  30.0   
4  2.0  2.52  73.0  0.0  0.0  0.0  38.0  4.0  71.1  296.0  49.0  23  20.0   

    HR    BB  IBB  HBP   WP   BK    SO    GB    FB    LD  IFFB  Balls  \
0  NaN   NaN  NaN  NaN  NaN  NaN   NaN   NaN   NaN   NaN   NaN    NaN   
1  9.0  28.0  0.0  1.0  1.0  0.0  49.0  54.0  64.0  28.0   5.0  361.0   
2  4.0  17.0  3.0  1.0  2.0  0.0  36.0  35.0  40.0  20.0   2.0  244.0   
3  4.0  35.0  2.0  5.0  3.0  0.0  49.0  59.0  51.0  24.0   7.0  397.0   
4  4.0  34.0  3.0  0.0  2.0  0.0  80.0  45.0  96.0  37.0   8.0  494.0   

   Strikes  Pitches    RS  IFH   BU  BUH    K/9  BB/9  K/BB    H/9  HR/9  \
0      NaN      NaN   NaN  NaN  NaN  NaN    NaN   NaN   NaN    NaN   NaN   
1    601.0    962.0  33.0  3.0  1.0  0.0   8.32  4.75  1.75   6.96  1.53   
2    364.0    608.0  10.0  3.0  2.0  0.0  10.02  4.73  2.12  10.86  1.11   
3    573.0    970.0  27.0  1.0  5.0  2.0   9.06  6.47  1.40   9.06  0.74   
4    775.0   1269.0   7.0  4.0  3.0  0.0  10.09  4.29  2.35   6.18  0.50   

     AVG  WHIP  BABIP   LOB%   FIP  GB/FB    LD%    GB%    FB%  IFFB%  HR/FB  \
0    NaN   NaN    NaN    NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN   
1  0.209  1.30  0.232  0.784  5.15   0.84  0.192  0.370  0.438  0.078  0.141   
2  0.293  1.73  0.376  0.642  4.29   0.88  0.211  0.368  0.421  0.050  0.100   
3  0.261  1.73  0.333  0.683  4.65   1.16  0.179  0.440  0.381  0.137  0.078   
4  0.187  1.16  0.253  0.775  3.01   0.47  0.208  0.253  0.539  0.083  0.042   

    IFH%  BUH%  
0    NaN   NaN  
1  0.056   0.0  
2  0.086   0.0  
3  0.017   0.4  
4  0.089   0.0

In [504]:
pitching_basic.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16575 entries, 0 to 16574
Data columns (total 58 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   name       16575 non-null  object 
 1   player_ID  16575 non-null  object 
 2   year_ID    16575 non-null  int64  
 3   team_ID    16575 non-null  object 
 4   lg_ID      16575 non-null  object 
 5   salary     16575 non-null  float64
 6   Age        11510 non-null  float64
 7   W          11510 non-null  float64
 8   L          11510 non-null  float64
 9   WAR        11510 non-null  float64
 10  ERA        11510 non-null  float64
 11  G          11510 non-null  float64
 12  GS         11510 non-null  float64
 13  CG         11510 non-null  float64
 14  ShO        11510 non-null  float64
 15  SV         11510 non-null  float64
 16  BS         10528 non-null  float64
 17  IP         11510 non-null  float64
 18  TBF        11510 non-null  float64
 19  H          11510 non-null  float64
 20  RA    

In [505]:
# check missing values
pitching_basic.isna().sum()

name            0
player_ID       0
year_ID         0
team_ID         0
lg_ID           0
salary          0
Age          5065
W            5065
L            5065
WAR          5065
ERA          5065
G            5065
GS           5065
CG           5065
ShO          5065
SV           5065
BS           6047
IP           5065
TBF          5065
H            5065
RA              0
ER           5065
HR           5065
BB           5065
IBB          5065
HBP          5065
WP           5065
BK           5065
SO           5065
GB           6047
FB           6047
LD           6047
IFFB         6047
Balls        6047
Strikes      6047
Pitches      6047
RS           6047
IFH          6047
BU           6047
BUH          6047
K/9          5065
BB/9         5065
K/BB         5065
H/9          5065
HR/9         5065
AVG          5065
WHIP         5065
BABIP        5065
LOB%         5065
FIP          5065
GB/FB        6047
LD%          6047
GB%          6047
FB%          6047
IFFB%        6047
HR/FB     

**Handling missing values in `pitching_basic`**

There are 5065 missing values for standard pitching statistics and is strange since there are missing values for age and other basic statistics. 

When checking these missing values in `pitching_basic`, there are fairly well-known players with missing statistics. This may be attributed to a scraping bug or data collection error on FanGraphs. 

While we could theoretically look up these players statistics, we'll just drop these missing rows from `pitching_basic`. 

In [508]:
# drop all missing nan rows
pitching_basic = pitching_basic.dropna()

In [509]:
# check
pitching_basic.isna().sum()

name         0
player_ID    0
year_ID      0
team_ID      0
lg_ID        0
salary       0
Age          0
W            0
L            0
WAR          0
ERA          0
G            0
GS           0
CG           0
ShO          0
SV           0
BS           0
IP           0
TBF          0
H            0
RA           0
ER           0
HR           0
BB           0
IBB          0
HBP          0
WP           0
BK           0
SO           0
GB           0
FB           0
LD           0
IFFB         0
Balls        0
Strikes      0
Pitches      0
RS           0
IFH          0
BU           0
BUH          0
K/9          0
BB/9         0
K/BB         0
H/9          0
HR/9         0
AVG          0
WHIP         0
BABIP        0
LOB%         0
FIP          0
GB/FB        0
LD%          0
GB%          0
FB%          0
IFFB%        0
HR/FB        0
IFH%         0
BUH%         0
dtype: int64

In [510]:
pitching_basic.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10528 entries, 1 to 16574
Data columns (total 58 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   name       10528 non-null  object 
 1   player_ID  10528 non-null  object 
 2   year_ID    10528 non-null  int64  
 3   team_ID    10528 non-null  object 
 4   lg_ID      10528 non-null  object 
 5   salary     10528 non-null  float64
 6   Age        10528 non-null  float64
 7   W          10528 non-null  float64
 8   L          10528 non-null  float64
 9   WAR        10528 non-null  float64
 10  ERA        10528 non-null  float64
 11  G          10528 non-null  float64
 12  GS         10528 non-null  float64
 13  CG         10528 non-null  float64
 14  ShO        10528 non-null  float64
 15  SV         10528 non-null  float64
 16  BS         10528 non-null  float64
 17  IP         10528 non-null  float64
 18  TBF        10528 non-null  float64
 19  H          10528 non-null  float64
 20  RA    

In [512]:
pitching_basic

name  player_ID  year_ID team_ID lg_ID     salary   Age    W  \
1      David Aardsma  aardsda01     2006     CHC    NL   300000.0  24.0  3.0   
2      David Aardsma  aardsda01     2007     CHW    AL   387500.0  25.0  2.0   
3      David Aardsma  aardsda01     2008     BOS    AL   403250.0  26.0  4.0   
4      David Aardsma  aardsda01     2009     SEA    AL   419000.0  27.0  3.0   
5      David Aardsma  aardsda01     2010     SEA    AL  2750000.0  28.0  0.0   
...              ...        ...      ...     ...   ...        ...   ...  ...   
16568    Joel Zumaya  zumayjo01     2007     DET    AL   410000.0  22.0  2.0   
16569    Joel Zumaya  zumayjo01     2008     DET    AL   420000.0  23.0  0.0   
16570    Joel Zumaya  zumayjo01     2009     DET    AL   735000.0  24.0  3.0   
16571    Joel Zumaya  zumayjo01     2010     DET    AL   915000.0  25.0  2.0   
16574      Tony Zych   zychto01     2017     SEA    AL   539600.0  26.0  6.0   

         L  WAR   ERA     G   GS   CG  ShO    SV   BS    IP    TBF     H  RA  \
1      0.0 -0.2  4.08  45.0  0.0  0.0  0.0   0.0  0.0  53.0  225.0  41.0  25   
2      1.0  0.2  6.40  25.0  0.0  0.0  0.0   0.0  3.0  32.1  151.0  39.0  24   
3      2.0 -0.1  5.55  47.0  0.0  0.0  0.0   0.0  1.0  48.2  228.0  49.0  32   
4      6.0  2.0  2.52  73.0  0.0  0.0  0.0  38.0  4.0  71.1  296.0  49.0  23   
5      6.0  0.3  3.44  53.0  0.0  0.0  0.0  31.0  5.0  49.2  202.0  33.0  19   
...    ...  ...   ...   ...  ...  ...  ...   ...  ...   ...    ...   ...  ..   
16568  3.0  0.2  4.28  28.0  0.0  0.0  0.0   1.0  4.0  33.2  142.0  23.0  16   
16569  2.0 -0.4  3.47  21.0  0.0  0.0  0.0   1.0  4.0  23.1  114.0  24.0  13   
16570  3.0 -0.2  4.94  29.0  0.0  0.0  0.0   1.0  6.0  31.0  149.0  34.0  18   
16571  1.0  1.1  2.35  31.0  0.0  0.0  0.0   1.0  2.0  38.1  156.0  32.0  13   
16574  3.0  0.3  2.66  45.0  0.0  0.0  0.0   1.0  1.0  40.2  173.0  30.0  12   

         ER   HR    BB  IBB  HBP   WP   BK    SO    GB    FB    LD  IFFB  \
1      24.0  9.0  28.0  0.0  1.0  1.0  0.0  49.0  54.0  64.0  28.0   5.0   
2      23.0  4.0  17.0  3.0  1.0  2.0  0.0  36.0  35.0  40.0  20.0   2.0   
3      30.0  4.0  35.0  2.0  5.0  3.0  0.0  49.0  59.0  51.0  24.0   7.0   
4      20.0  4.0  34.0  3.0  0.0  2.0  0.0  80.0  45.0  96.0  37.0   8.0   
5      19.0  5.0  25.0  5.0  2.0  2.0  0.0  49.0  42.0  53.0  23.0   4.0   
...     ...  ...   ...  ...  ...  ...  ...   ...   ...   ...   ...   ...   
16568  16.0  3.0  17.0  2.0  1.0  3.0  0.0  27.0  35.0  46.0  15.0   6.0   
16569   9.0  3.0  22.0  4.0  0.0  6.0  0.0  22.0  28.0  28.0  14.0   2.0   
16570  17.0  5.0  22.0  3.0  1.0  1.0  0.0  30.0  32.0  48.0  13.0   3.0   
16571  10.0  1.0  11.0  0.0  0.0  2.0  0.0  34.0  40.0  51.0  17.0   7.0   
16574  12.0  2.0  21.0  3.0  5.0  1.0  1.0  35.0  55.0  33.0  23.0   6.0   

       Balls  Strikes  Pitches    RS  IFH   BU  BUH    K/9  BB/9  K/BB    H/9  \
1      361.0    601.0    962.0  33.0  3.0  1.0  0.0   8.32  4.75  1.75   6.96   
2      244.0    364.0    608.0  10.0  3.0  2.0  0.0  10.02  4.73  2.12  10.86   
3      397.0    573.0    970.0  27.0  1.0  5.0  2.0   9.06  6.47  1.40   9.06   
4      494.0    775.0   1269.0   7.0  4.0  3.0  0.0  10.09  4.29  2.35   6.18   
5      337.0    530.0    867.0   2.0  0.0  8.0  1.0   8.88  4.53  1.96   5.98   
...      ...      ...      ...   ...  ...  ...  ...    ...   ...   ...    ...   
16568  211.0    342.0    553.0   8.0  1.0  1.0  0.0   7.22  4.54  1.59   6.15   
16569  192.0    258.0    450.0  12.0  3.0  0.0  0.0   8.49  8.49  1.00   9.26   
16570  215.0    368.0    583.0  19.0  2.0  3.0  1.0   8.71  6.39  1.36   9.87   
16571  224.0    373.0    597.0  32.0  3.0  3.0  0.0   7.98  2.58  3.09   7.51   
16574  228.0    411.0    639.0  31.0  1.0  1.0  0.0   7.75  4.65  1.67   6.64   

       HR/9    AVG  WHIP  BABIP   LOB%   FIP  GB/FB    LD%    GB%    FB%  \
1      1.53  0.209  1.30  0.232  0.784  5.15   0.84  0.192  0.370  0.438   
2      1.11  0.293  1.73  0.376  0.642  4.29   0.88  0.2

**Save `pitching_basic` as a csv**

In [511]:
path = "Data/"

pitching_basic.to_csv(path + 'pitching_basic')

**Checking and cleaning `batting_adv`:**

In [404]:
batting_adv.head(3)

name  player_ID  year_ID team_ID lg_ID    salary   Age  \
0         Jeff Abbott  abbotje01     2000     CHW    AL  255000.0  27.0   
1         Kurt Abbott  abbotku01     2000     NYM    NL  500000.0  31.0   
2  Reggie Abercrombie  abercre01     2006     FLA    NL  327000.0  24.0   

       G     AB     PA    AVG     H    1B    2B   3B   HR     R   RBI    BB  \
0   80.0  215.0  242.0  0.274  59.0  40.0  15.0  1.0  3.0  31.0  29.0  21.0   
1   79.0  157.0  173.0  0.217  34.0  20.0   7.0  1.0  6.0  22.0  12.0  14.0   
2  111.0  255.0  281.0  0.212  54.0  35.0  12.0  2.0  5.0  39.0  24.0  18.0   

   IBB    SO  HBP   SF   SH  GDP   SB   CS    BB%     K%  BB/K    OBP    SLG  \
0  1.0  38.0  2.0  1.0  2.0  2.0  2.0  1.0  0.087  0.157  0.55  0.343  0.395   
1  2.0  51.0  1.0  1.0  0.0  2.0  1.0  1.0  0.081  0.295  0.27  0.283  0.389   
2  2.0  78.0  3.0  1.0  4.0  2.0  6.0  5.0  0.064  0.278  0.23  0.271  0.333   

     OPS    ISO  BABIP  runs_above_avg  runs_above_avg_off  \
0  0.738  0.121  0.320           -12.6                -6.7   
1  0.672  0.172  0.277            -9.1                -6.8   
2  0.604  0.122  0.283           -15.6               -11.6   

   runs_above_avg_def  WAR_rep   WAA   WAR    GB    FB    LD  IFFB  Pitches  \
0                -7.3     0.84 -1.13 -0.29   NaN   NaN   NaN   NaN      NaN   
1                 0.6     0.52 -0.93 -0.41   NaN   NaN   NaN   NaN      NaN   
2                -3.1     0.84 -1.58 -0.74  93.0  59.0  19.0   9.0    990.0   

   Balls  Strikes   IFH    BU  BUH    BB%     K%  BB/K    OBP    SLG    OPS  \
0    NaN      NaN   NaN   NaN  NaN  0.087  0.157  0.55  0.343  0.395  0.738   
1    NaN      NaN   NaN   NaN  NaN  0.081  0.295  0.27  0.283  0.389  0.672   
2  307.0    683.0  11.0  11.0  5.0  0.064  0.278  0.23  0.271  0.333  0.604   

     ISO  BABIP   GB/FB    LD%    GB%    FB%  IFFB%  HR/FB   IFH%   BUH%  \
0  0.121  0.320     NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
1  0.172  0.277     NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
2  0.122  0.283  0.0158  0.111  0.544  0.345  0.153  0.085  0.118  0.455   

    wOBA  wRAA   wRC   Bat  Fld  Rep  Pos   RAR  Spd  wRC+   WPA  -WPA  +WPA  \
0  0.328  -2.7  29.0  -4.2 -5.0  7.8 -1.6  -2.1  3.9  87.0  0.37 -3.89  4.26   
1  0.289  -7.8  15.0  -7.7 -2.0  5.6  1.5  -2.6  4.2  67.0 -0.40 -3.05  2.65   
2  0.264 -16.3  19.0 -16.9 -5.6  8.8  0.9 -10.3  6.2  54.0 -1.40 -5.31  3.90   

    RE24   REW   pLI  phLI    PH  WPA/LI  Clutch  FB% (Pitch)   FBv    SL%  \
0  -6.74 -0.57  0.90  1.79  14.0   -0.16    0.57          NaN   NaN    NaN   
1 -12.42 -1.20  0.95  1.12  16.0   -0.88    0.46          NaN   NaN    NaN   
2 -12.00 -1.18  0.96  0.98  10.0   -0.94   -0.52        0.524  89.8  0.254   

    SLv    CT%   CTv    CB%   CBv    CH%   CHv    SF%   SFv  KN%  KNv    XX%  \
0   NaN    NaN   NaN    NaN   NaN    NaN   NaN    NaN   NaN  NaN  NaN    NaN   
1   NaN    NaN   NaN    NaN   NaN    NaN   NaN    NaN   NaN  NaN  NaN    NaN   
2  82.3  0.024  86.5  0.091  74.3  0.102  79.2  0.005  87.8  NaN  NaN  0.029   

   PO%   wFB  wSL  wCT  wCB  wCH  wSF  wKN  wFB/C  wSL/C  wCT/C  wCB/C  wCH/C  \
0  NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN    NaN    NaN    NaN    NaN    NaN   
1  NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN    NaN    NaN    NaN    NaN    NaN   
2  NaN -10.0  1.4 -1.9 -4.3  2.3 -0.3  NaN  -1.98   0.56   -8.1   -4.9   2.36   

   wSF/C  wKN/C  O-Swing%  Z-Swing%  Swing%  O-Contact%  Z-Contact%  Contact%  \
0    NaN    NaN       NaN       NaN     NaN         NaN         NaN       NaN   
1    NaN    NaN       NaN       NaN     NaN         NaN         NaN       NaN   
2   -6.0    NaN     0.383     0.794   0.589       0.452       0.779     0.673   

   Zone%  F-Strike%  SwStr%  BsR  FA% (sc)  FT% (sc)  FC% (sc)  FS% (sc)  \
0    NaN        NaN     NaN  0.0       NaN       NaN       NaN       NaN   
1    NaN        NaN     NaN -0.2       NaN       NaN       NaN       NaN   
2    0.5      0.719   0.191  1.8       NaN       NaN     

In [405]:
# check missing values
batting_adv.isna().sum()

name            0
player_ID       0
year_ID         0
team_ID         0
lg_ID           0
             ... 
HardHit      4268
HardHit%     8877
Events        314
CStr%        1477
CSW%         1477
Length: 330, dtype: int64

**Handling missing values in `batting_adv`**

Unfortunately, we have many missing values in the `batting_adv` table. This is expected, since there is a lot of variance when it comes to collecting advanced StatCast data. 

Lets limit `batting_adv` to data between 2014 and 2021 and fill in the remaining missing values with 0s. 

In [420]:
batting_adv = batting_adv[batting_adv['year_ID'] >= 2014]

In [421]:
# remove rows where stats were not scraped properly (same as in batting_basic table)
# rows where 
batting_adv = batting_adv[batting_adv['Age'].notna()]

In [422]:
# fill all missing NaNs with 0
batting_adv = batting_adv.fillna(0)

In [423]:
batting_adv

name  player_ID  year_ID team_ID lg_ID     salary   Age  \
22       Bobby Abreu  abreubo01     2014     NYM    NL  9000000.0  40.0   
39     Dustin Ackley  ackledu01     2014     SEA    AL  1700000.0  26.0   
40     Dustin Ackley  ackledu01     2015     NYY    AL  1700000.0  27.0   
41     Dustin Ackley  ackledu01     2015     SEA    AL  2600000.0  27.0   
42     Dustin Ackley  ackledu01     2016     NYY    AL  3200000.0  28.0   
...              ...        ...      ...     ...   ...        ...   ...   
12649    Mike Zunino  zuninmi01     2017     SEA    AL   570000.0  26.0   
12650    Mike Zunino  zuninmi01     2018     SEA    AL  2975000.0  27.0   
12651    Mike Zunino  zuninmi01     2019     TBR    AL  4412000.0  28.0   
12652    Mike Zunino  zuninmi01     2020     TBR    AL  4500000.0  29.0   
12653    Mike Zunino  zuninmi01     2021     TBR    AL  2000000.0  30.0   

           G     AB     PA    AVG      H    1B    2B   3B    HR     R   RBI  \
22      78.0  133.0  155.0  0.248   33.0  23.0   9.0  0.0   1.0  12.0  14.0   
39     143.0  502.0  542.0  0.245  123.0  78.0  27.0  4.0  14.0  64.0  65.0   
40     108.0  238.0  264.0  0.231   55.0  31.0  11.0  3.0  10.0  28.0  30.0   
41     108.0  238.0  264.0  0.231   55.0  31.0  11.0  3.0  10.0  28.0  30.0   
42      28.0   61.0   70.0  0.148    9.0   9.0   0.0  0.0   0.0   6.0   4.0   
...      ...    ...    ...    ...    ...   ...   ...  ...   ...   ...   ...   
12649  124.0  387.0  435.0  0.251   97.0  47.0  25.0  0.0  25.0  52.0  64.0   
12650  113.0  373.0  405.0  0.201   75.0  37.0  18.0  0.0  20.0  37.0  44.0   
12651   90.0  266.0  289.0  0.165   44.0  24.0  10.0  1.0   9.0  30.0  32.0   
12652   28.0   75.0   84.0  0.147   11.0   3.0   4.0  0.0   4.0   8.0  10.0   
12653  109.0  333.0  375.0  0.216   72.0  26.0  11.0  2.0  33.0  64.0  62.0   

         BB  IBB     SO  HBP   SF   SH   GDP   SB   CS    BB%     K%  BB/K  \
22     20.0  0.0   21.0  0.0  2.0  0.0   3.0  1.0  0.0  0.129  0.135  0.95   
39     32.0  1.0   90.0  3.0  2.0  3.0  10.0  8.0  4.0  0.059  0.166  0.36   
40     18.0  0.0   45.0  1.0  4.0  3.0   3.0  2.0  2.0  0.068  0.170  0.40   
41     18.0  0.0   45.0  1.0  4.0  3.0   3.0  2.0  2.0  0.068  0.170  0.40   
42      8.0  0.0    9.0  0.0  1.0  0.0   0.0  0.0  0.0  0.114  0.129  0.89   
...     ...  ...    ...  ...  ...  ...   ...  ...  ...    ...    ...   ...   
12649  39.0  0.0  160.0  8.0  1.0  0.0   8.0  1.0  0.0  0.090  0.368  0.24   
12650  24.0  0.0  150.0  6.0  2.0  0.0   7.0  0.0  0.0  0.059  0.370  0.16   
12651  20.0  0.0   98.0  3.0  0.0  0.0   4.0  0.0  0.0  0.069  0.339  0.20   
12652   6.0  0.0   37.0  3.0  0.0  0.0   0.0  0.0  0.0  0.071  0.440  0.16   
12653  34.0  0.0  132.0  7.0  1.0  0.0   7.0  0.0  0.0  0.091  0.352  0.26   

         OBP    SLG    OPS    ISO  BABIP  runs_above_avg  runs_above_avg_off  \
22     0.342  0.338  0.680  0.090  0.283            -8.4                -1.4   
39     0.293  0.398  0.692  0.153  0.273            -1.9                -8.9   
40     0.284  0.429  0.712  0.197  0.241            -0.6                 3.4   
41     0.284  0.429  0.712  0.197  0.241           -17.8                -8.8   
42     0.243  0.148  0.390  0.000  0.170            -4.0                -8.0   
...      ...    ...    ...    ...    ...             ...                 ...   
12649  0.331  0.509  0.840  0.258  0.355            18.6                17.6   
12650  0.259  0.410  0.669  0.209  0.268             2.9                -4.1   
12651  0.232  0.312  0.544  0.147  0.220           -13.0               -17.0   
12652  0.238  0.360  0.598  0.213  0.206            -3.3                -2.3   
12653  0.301  0.559  0.860  0.342  0.231            24.5                25.5   

       runs_above_avg_def  WAR_rep   WAA   WAR     GB     FB    LD  IFFB  \
22                   -8.5     0.50 -0.99 -0.49   56.0   33.0  25.0   0.0   
39                    1.0     1.89 -0.02  1.87  187.0  150.0  76.0  14.0   
40                   -4.4     0.20 -0.04

**Save `batting_adv` as a csv**

In [424]:
path = "Data/"

batting_adv.to_csv(path + 'batting_adv')

## Collect Team Statistics since 1960

Below we will import team batting, pitching, and fielding statistics since 1960. 

1960 will be used as a benchmark as this was approximately the time when baseball started its 'Expansion Era'. In other words, baseball implemented new rules close to what we see to this day and expanded to 30 teams. 

In [245]:
from pybaseball import team_batting

# get each team's seasonal batting stats from 1960 through 2021
team_batting = team_batting(1960, 2021)

In [246]:
team_batting

teamIDfg  Season Team  Age     G    AB    PA     H    1B   2B  3B   HR  \
0           11    1996  SEA   28  1736  5668  6518  1625  1018  343  19  245   
1            5    1996  CLE   30  1705  5681  6486  1665  1089  335  23  218   
2            5    1999  CLE   30  1859  5634  6554  1629  1079  309  32  209   
3            5    1995  CLE   29  1527  5028  5686  1461   952  279  23  207   
4            9    1994  NYY   30  1192  3986  4611  1155   762  238  16  139   
...        ...     ...  ...  ...   ...   ...   ...   ...   ...  ...  ..  ...   
1637        25    1965  NYM   26  2316  5441  5976  1202   865  203  27  107   
1638        25    1963  NYM   27  2171  5336  5921  1168   881  156  35   96   
1639        13    1972  TEX   26  2068  5029  5680  1092   853  166  17   56   
1640        21    1964  HOU   26  1948  5303  5859  1214   941  162  41   70   
1641        21    1963  HOU   26  1995  5384  5983  1184   913  170  39   62   

         R  RBI   BB  IBB    SO  HBP  SF  SH  GDP   SB  CS    AVG  GB  FB  LD  \
0      993  954  670   57  1052   75  58  46  121   90  39  0.287 NaN NaN NaN   
1      952  904  671   44   844   43  57  34  164  160  50  0.293 NaN NaN NaN   
2     1009  960  743   41  1099   55  67  54  136  147  50  0.289 NaN NaN NaN   
3      840  803  542   40   766   35  48  31  128  132  53  0.291 NaN NaN NaN   
4      670  632  530   34   660   31  37  27  112   55  40  0.290 NaN NaN NaN   
...    ...  ...  ...  ...   ...  ...  ..  ..  ...  ...  ..    ...  ..  ..  ..   
1637   495  460  392   40  1129   39  28  76  121   28  42  0.221 NaN NaN NaN   
1638   501  459  457   41  1078   47  35  46  106   41  52  0.219 NaN NaN NaN   
1639   461  424  503   41   926   30  34  84  100  126  73  0.217 NaN NaN NaN   
1640   495  452  381   44   872   49  39  87  113   40  48  0.229 NaN NaN NaN   
1641   464  420  456   39   938   30  27  86  119   39  30  0.220 NaN NaN NaN   

      IFFB  Pitches  Balls  Strikes  IFH  BU  BUH    BB%     K%  BB/K    OBP  \
0      NaN      NaN    NaN      NaN  NaN NaN  NaN  0.103  0.161  0.64  0.366   
1      NaN      NaN    NaN      NaN  NaN NaN  NaN  0.103  0.130  0.80  0.369   
2      NaN      NaN    NaN      NaN  NaN NaN  NaN  0.113  0.168  0.68  0.373   
3      NaN      NaN    NaN      NaN  NaN NaN  NaN  0.095  0.135  0.71  0.361   
4      NaN      NaN    NaN      NaN  NaN NaN  NaN  0.115  0.143  0.80  0.374   
...    ...      ...    ...      ...  ...  ..  ...    ...    ...   ...    ...   
1637   NaN      NaN    NaN      NaN  NaN NaN  NaN  0.066  0.189  0.35  0.277   
1638   NaN      NaN    NaN      NaN  NaN NaN  NaN  0.077  0.182  0.42  0.285   
1639   NaN      NaN    NaN      NaN  NaN NaN  NaN  0.089  0.163  0.54  0.290   
1640   NaN      NaN    NaN      NaN  NaN NaN  NaN  0.065  0.149  0.44  0.285   
1641   NaN      NaN    NaN      NaN  NaN NaN  NaN  0.076  0.157  0.49  0.283   

        SLG    OPS    ISO  BABIP  GB/FB  LD%  GB%  FB%  IFFB%  HR/FB  IFH%  \
0     0.484  0.850  0.197  0.312    NaN  NaN  NaN  NaN    NaN    NaN   NaN   
1     0.475  0.844  0.182  0.309    NaN  NaN  NaN  NaN    NaN    NaN   NaN   
2     0.467  0.840  0.177  0.323    NaN  NaN  NaN  NaN    NaN    NaN   NaN   
3     0.479  0.839  0.188  0.306    NaN  NaN  NaN  NaN    NaN    NaN   NaN   
4     0.462  0.836  0.172  0.315    NaN  NaN  NaN  NaN    NaN    NaN   NaN   
...     ...    ...    ...    ...    ...  ...  ...  ...    ...    ...   ...   
1637  0.327  0.604  0.106  0.259    NaN  NaN  NaN  NaN    NaN    NaN   NaN   
1638  0.315  0.600  0.096  0.255    NaN  NaN  NaN  NaN    NaN    NaN   NaN   
1639  0.290  0.581  0.073  0.254    NaN  NaN  NaN  NaN    NaN    NaN   NaN   
1640  0.315  0.599  0.086  0.260    NaN  NaN  NaN  NaN    NaN    NaN   NaN   
1641  0.301  0.584  0.081  0.254    NaN  NaN  NaN  NaN    NaN    NaN   NaN   

      BUH%   wOBA   wRAA   wRC    Bat   Fld    Rep   Pos    RAR   WAR  Dol  \
0      NaN  0.367  178.6  1018  110.7  52.0  207.3 -18.9  389.7  37.1  NaN   
1      NaN  0.367 

In [247]:
from pybaseball import team_pitching

# get each team's individual-season-level pitching stats from 1960 through 2021
team_pitching = team_pitching(1960, 2021)

In [248]:
team_pitching

teamIDfg  Season Team  Age     G    AB    PA     H    1B   2B  3B   HR  \
0           11    1996  SEA   28  1736  5668  6518  1625  1018  343  19  245   
1            5    1996  CLE   30  1705  5681  6486  1665  1089  335  23  218   
2            5    1999  CLE   30  1859  5634  6554  1629  1079  309  32  209   
3            5    1995  CLE   29  1527  5028  5686  1461   952  279  23  207   
4            9    1994  NYY   30  1192  3986  4611  1155   762  238  16  139   
...        ...     ...  ...  ...   ...   ...   ...   ...   ...  ...  ..  ...   
1637        25    1965  NYM   26  2316  5441  5976  1202   865  203  27  107   
1638        25    1963  NYM   27  2171  5336  5921  1168   881  156  35   96   
1639        13    1972  TEX   26  2068  5029  5680  1092   853  166  17   56   
1640        21    1964  HOU   26  1948  5303  5859  1214   941  162  41   70   
1641        21    1963  HOU   26  1995  5384  5983  1184   913  170  39   62   

         R  RBI   BB  IBB    SO  HBP  SF  SH  GDP   SB  CS    AVG  GB  FB  LD  \
0      993  954  670   57  1052   75  58  46  121   90  39  0.287 NaN NaN NaN   
1      952  904  671   44   844   43  57  34  164  160  50  0.293 NaN NaN NaN   
2     1009  960  743   41  1099   55  67  54  136  147  50  0.289 NaN NaN NaN   
3      840  803  542   40   766   35  48  31  128  132  53  0.291 NaN NaN NaN   
4      670  632  530   34   660   31  37  27  112   55  40  0.290 NaN NaN NaN   
...    ...  ...  ...  ...   ...  ...  ..  ..  ...  ...  ..    ...  ..  ..  ..   
1637   495  460  392   40  1129   39  28  76  121   28  42  0.221 NaN NaN NaN   
1638   501  459  457   41  1078   47  35  46  106   41  52  0.219 NaN NaN NaN   
1639   461  424  503   41   926   30  34  84  100  126  73  0.217 NaN NaN NaN   
1640   495  452  381   44   872   49  39  87  113   40  48  0.229 NaN NaN NaN   
1641   464  420  456   39   938   30  27  86  119   39  30  0.220 NaN NaN NaN   

      IFFB  Pitches  Balls  Strikes  IFH  BU  BUH    BB%     K%  BB/K    OBP  \
0      NaN      NaN    NaN      NaN  NaN NaN  NaN  0.103  0.161  0.64  0.366   
1      NaN      NaN    NaN      NaN  NaN NaN  NaN  0.103  0.130  0.80  0.369   
2      NaN      NaN    NaN      NaN  NaN NaN  NaN  0.113  0.168  0.68  0.373   
3      NaN      NaN    NaN      NaN  NaN NaN  NaN  0.095  0.135  0.71  0.361   
4      NaN      NaN    NaN      NaN  NaN NaN  NaN  0.115  0.143  0.80  0.374   
...    ...      ...    ...      ...  ...  ..  ...    ...    ...   ...    ...   
1637   NaN      NaN    NaN      NaN  NaN NaN  NaN  0.066  0.189  0.35  0.277   
1638   NaN      NaN    NaN      NaN  NaN NaN  NaN  0.077  0.182  0.42  0.285   
1639   NaN      NaN    NaN      NaN  NaN NaN  NaN  0.089  0.163  0.54  0.290   
1640   NaN      NaN    NaN      NaN  NaN NaN  NaN  0.065  0.149  0.44  0.285   
1641   NaN      NaN    NaN      NaN  NaN NaN  NaN  0.076  0.157  0.49  0.283   

        SLG    OPS    ISO  BABIP  GB/FB  LD%  GB%  FB%  IFFB%  HR/FB  IFH%  \
0     0.484  0.850  0.197  0.312    NaN  NaN  NaN  NaN    NaN    NaN   NaN   
1     0.475  0.844  0.182  0.309    NaN  NaN  NaN  NaN    NaN    NaN   NaN   
2     0.467  0.840  0.177  0.323    NaN  NaN  NaN  NaN    NaN    NaN   NaN   
3     0.479  0.839  0.188  0.306    NaN  NaN  NaN  NaN    NaN    NaN   NaN   
4     0.462  0.836  0.172  0.315    NaN  NaN  NaN  NaN    NaN    NaN   NaN   
...     ...    ...    ...    ...    ...  ...  ...  ...    ...    ...   ...   
1637  0.327  0.604  0.106  0.259    NaN  NaN  NaN  NaN    NaN    NaN   NaN   
1638  0.315  0.600  0.096  0.255    NaN  NaN  NaN  NaN    NaN    NaN   NaN   
1639  0.290  0.581  0.073  0.254    NaN  NaN  NaN  NaN    NaN    NaN   NaN   
1640  0.315  0.599  0.086  0.260    NaN  NaN  NaN  NaN    NaN    NaN   NaN   
1641  0.301  0.584  0.081  0.254    NaN  NaN  NaN  NaN    NaN    NaN   NaN   

      BUH%   wOBA   wRAA   wRC    Bat   Fld    Rep   Pos    RAR   WAR   Dol  \
0      NaN  0.367  178.6  1018  110.7  52.0  207.3 -18.9  389.7  37.1  None   
1      NaN  0.36

In [249]:
from pybaseball import team_fielding

# get each team's seasonal fielding stats from 1960 through 2021
team_fielding = team_fielding(1960, 2021)

In [250]:
team_fielding

teamIDfg  Season Team  Age     G    AB    PA     H    1B   2B  3B   HR  \
0           11    1996  SEA   28  1736  5668  6518  1625  1018  343  19  245   
1            5    1996  CLE   30  1705  5681  6486  1665  1089  335  23  218   
2            5    1999  CLE   30  1859  5634  6554  1629  1079  309  32  209   
3            5    1995  CLE   29  1527  5028  5686  1461   952  279  23  207   
4            9    1994  NYY   30  1192  3986  4611  1155   762  238  16  139   
...        ...     ...  ...  ...   ...   ...   ...   ...   ...  ...  ..  ...   
1637        25    1965  NYM   26  2316  5441  5976  1202   865  203  27  107   
1638        25    1963  NYM   27  2171  5336  5921  1168   881  156  35   96   
1639        13    1972  TEX   26  2068  5029  5680  1092   853  166  17   56   
1640        21    1964  HOU   26  1948  5303  5859  1214   941  162  41   70   
1641        21    1963  HOU   26  1995  5384  5983  1184   913  170  39   62   

         R  RBI   BB  IBB    SO  HBP  SF  SH  GDP   SB  CS    AVG  GB  FB  LD  \
0      993  954  670   57  1052   75  58  46  121   90  39  0.287 NaN NaN NaN   
1      952  904  671   44   844   43  57  34  164  160  50  0.293 NaN NaN NaN   
2     1009  960  743   41  1099   55  67  54  136  147  50  0.289 NaN NaN NaN   
3      840  803  542   40   766   35  48  31  128  132  53  0.291 NaN NaN NaN   
4      670  632  530   34   660   31  37  27  112   55  40  0.290 NaN NaN NaN   
...    ...  ...  ...  ...   ...  ...  ..  ..  ...  ...  ..    ...  ..  ..  ..   
1637   495  460  392   40  1129   39  28  76  121   28  42  0.221 NaN NaN NaN   
1638   501  459  457   41  1078   47  35  46  106   41  52  0.219 NaN NaN NaN   
1639   461  424  503   41   926   30  34  84  100  126  73  0.217 NaN NaN NaN   
1640   495  452  381   44   872   49  39  87  113   40  48  0.229 NaN NaN NaN   
1641   464  420  456   39   938   30  27  86  119   39  30  0.220 NaN NaN NaN   

      IFFB  Pitches  Balls  Strikes  IFH  BU  BUH    BB%     K%  BB/K    OBP  \
0      NaN      NaN    NaN      NaN  NaN NaN  NaN  0.103  0.161  0.64  0.366   
1      NaN      NaN    NaN      NaN  NaN NaN  NaN  0.103  0.130  0.80  0.369   
2      NaN      NaN    NaN      NaN  NaN NaN  NaN  0.113  0.168  0.68  0.373   
3      NaN      NaN    NaN      NaN  NaN NaN  NaN  0.095  0.135  0.71  0.361   
4      NaN      NaN    NaN      NaN  NaN NaN  NaN  0.115  0.143  0.80  0.374   
...    ...      ...    ...      ...  ...  ..  ...    ...    ...   ...    ...   
1637   NaN      NaN    NaN      NaN  NaN NaN  NaN  0.066  0.189  0.35  0.277   
1638   NaN      NaN    NaN      NaN  NaN NaN  NaN  0.077  0.182  0.42  0.285   
1639   NaN      NaN    NaN      NaN  NaN NaN  NaN  0.089  0.163  0.54  0.290   
1640   NaN      NaN    NaN      NaN  NaN NaN  NaN  0.065  0.149  0.44  0.285   
1641   NaN      NaN    NaN      NaN  NaN NaN  NaN  0.076  0.157  0.49  0.283   

        SLG    OPS    ISO  BABIP  GB/FB  LD%  GB%  FB%  IFFB%  HR/FB  IFH%  \
0     0.484  0.850  0.197  0.312    NaN  NaN  NaN  NaN    NaN    NaN   NaN   
1     0.475  0.844  0.182  0.309    NaN  NaN  NaN  NaN    NaN    NaN   NaN   
2     0.467  0.840  0.177  0.323    NaN  NaN  NaN  NaN    NaN    NaN   NaN   
3     0.479  0.839  0.188  0.306    NaN  NaN  NaN  NaN    NaN    NaN   NaN   
4     0.462  0.836  0.172  0.315    NaN  NaN  NaN  NaN    NaN    NaN   NaN   
...     ...    ...    ...    ...    ...  ...  ...  ...    ...    ...   ...   
1637  0.327  0.604  0.106  0.259    NaN  NaN  NaN  NaN    NaN    NaN   NaN   
1638  0.315  0.600  0.096  0.255    NaN  NaN  NaN  NaN    NaN    NaN   NaN   
1639  0.290  0.581  0.073  0.254    NaN  NaN  NaN  NaN    NaN    NaN   NaN   
1640  0.315  0.599  0.086  0.260    NaN  NaN  NaN  NaN    NaN    NaN   NaN   
1641  0.301  0.584  0.081  0.254    NaN  NaN  NaN  NaN    NaN    NaN   NaN   

      BUH%   wOBA   wRAA   wRC    Bat   Fld    Rep   Pos    RAR   WAR   Dol  \
0      NaN  0.367  178.6  1018  110.7  52.0  207.3 -18.9  389.7  37.1  None   
1      NaN  0.36